<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HEMP Using R - 5&nbsp; 이분 문항반응이론</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chap06.html" rel="next">
<link href="./chap04.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">이분 문항반응이론</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">HEMP Using R</a> 
        <div class="sidebar-tools-main">
    <a href="./HEMP-Using-R.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">머리말</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R 소개</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">고전검사이론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">일반화가능도 이론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">측정에서 요인분석적 접근</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap05.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">이분 문항반응이론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">다분 문항반응이론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">다차원 문항반응이론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">설명적 문항반응이론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">데이터 시각화 및 측정 모델</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">동등화</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">측정 불변성과 차별기능문항</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">측정의 고급 주제</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#개요" id="toc-개요" class="nav-link active" data-scroll-target="#개요"><span class="toc-section-number">5.1</span>  개요</a></li>
  <li><a href="#소개" id="toc-소개" class="nav-link" data-scroll-target="#소개"><span class="toc-section-number">5.2</span>  소개</a>
  <ul class="collapse">
  <li><a href="#고전검사이론과의-비교" id="toc-고전검사이론과의-비교" class="nav-link" data-scroll-target="#고전검사이론과의-비교"><span class="toc-section-number">5.2.1</span>  고전검사이론과의 비교</a></li>
  <li><a href="#irt의-기본-개념" id="toc-irt의-기본-개념" class="nav-link" data-scroll-target="#irt의-기본-개념"><span class="toc-section-number">5.2.2</span>  IRT의 기본 개념</a></li>
  <li><a href="#irt-모델의-가정" id="toc-irt-모델의-가정" class="nav-link" data-scroll-target="#irt-모델의-가정"><span class="toc-section-number">5.2.3</span>  IRT 모델의 가정</a></li>
  </ul></li>
  <li><a href="#이분-문항에-대한-단일-차원-irt-모델" id="toc-이분-문항에-대한-단일-차원-irt-모델" class="nav-link" data-scroll-target="#이분-문항에-대한-단일-차원-irt-모델"><span class="toc-section-number">5.3</span>  이분 문항에 대한 단일 차원 IRT 모델</a>
  <ul class="collapse">
  <li><a href="#모수-로지스틱-모델과-rasch-모델" id="toc-모수-로지스틱-모델과-rasch-모델" class="nav-link" data-scroll-target="#모수-로지스틱-모델과-rasch-모델"><span class="toc-section-number">5.3.1</span>  1모수 로지스틱 모델과 Rasch 모델</a></li>
  <li><a href="#모수-로지스틱-모델-1" id="toc-모수-로지스틱-모델-1" class="nav-link" data-scroll-target="#모수-로지스틱-모델-1"><span class="toc-section-number">5.3.2</span>  2모수 로지스틱 모델</a></li>
  <li><a href="#모수-로지스틱-모델-2" id="toc-모수-로지스틱-모델-2" class="nav-link" data-scroll-target="#모수-로지스틱-모델-2"><span class="toc-section-number">5.3.3</span>  3모수 로지스틱 모델</a></li>
  <li><a href="#모수-로지스틱-모델-3" id="toc-모수-로지스틱-모델-3" class="nav-link" data-scroll-target="#모수-로지스틱-모델-3"><span class="toc-section-number">5.3.4</span>  4모수 로지스틱 모델</a></li>
  </ul></li>
  <li><a href="#irt-모델에서-능력-추정" id="toc-irt-모델에서-능력-추정" class="nav-link" data-scroll-target="#irt-모델에서-능력-추정"><span class="toc-section-number">5.4</span>  IRT 모델에서 능력 추정</a></li>
  <li><a href="#모델-진단" id="toc-모델-진단" class="nav-link" data-scroll-target="#모델-진단"><span class="toc-section-number">5.5</span>  모델 진단</a>
  <ul class="collapse">
  <li><a href="#문항-적합" id="toc-문항-적합" class="nav-link" data-scroll-target="#문항-적합"><span class="toc-section-number">5.5.1</span>  문항 적합</a></li>
  <li><a href="#피험자-적합도" id="toc-피험자-적합도" class="nav-link" data-scroll-target="#피험자-적합도"><span class="toc-section-number">5.5.2</span>  피험자 적합도</a></li>
  <li><a href="#모델-선택" id="toc-모델-선택" class="nav-link" data-scroll-target="#모델-선택"><span class="toc-section-number">5.5.3</span>  모델 선택</a></li>
  </ul></li>
  <li><a href="#요약" id="toc-요약" class="nav-link" data-scroll-target="#요약"><span class="toc-section-number">5.6</span>  요약</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">이분 문항반응이론</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="개요" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="개요"><span class="header-section-number">5.1</span> 개요</h2>
<p>이 장에서는 이분법적으로 채점된 문항에 대한 단일차원 문항 반응 이론(IRT) 모델을 소개합니다. 이 장은 IRT 프레임워크에 대한 간략한 설명으로 시작됩니다. 이 장의 나머지 부분은 다음과 같이 진행됩니다: 수학적 공식과 함께 단일차원 IRT 모델을 간략하게 소개하고, 해석을 용이하게 하기 위해 모수를 설명한 다음, 마지막으로 이분법적 문항에 대한 단일차원 IRT 모델을 추정하고 정보를 추출하는 방법을 보여주는 R 예제를 제시합니다. 이 장에서 다루는 IRT 모델에는 라쉬 모델, 1-모수, 2-모수, 3-모수 및 4-모수 IRT 모델이 포함됩니다. CRAN에는 IRT 모델에 적합한 <strong>eRm</strong>(Mair &amp; Hatzinger, 2007a), <strong>ltm</strong>(Rizopoulos, 2006), <strong>mirt</strong>(Chalmers, 2012), <strong>TAM</strong>(Kiefer, Robitzsch, &amp; Wu, 2016) 등과 같은 여러 사용자 패키지가 존재합니다. 이 장에서는 다양한 IRT 모델을 추정할 수 있는 가장 포괄적이고 최신의 R 패키지인 mirt 패키지(Chalmers, 2012)를 사용하여 단일차원 IRT 모델을 추정하는 방법을 설명합니다.</p>
</section>
<section id="소개" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="소개"><span class="header-section-number">5.2</span> 소개</h2>
<section id="고전검사이론과의-비교" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="고전검사이론과의-비교"><span class="header-section-number">5.2.1</span> 고전검사이론과의 비교</h3>
<p>제2장에서는 고전검사이론(CTT) 모델을 소개했습니다. IRT는 CTT 모델의 단점을 극복하기 위해 개발되었습니다. 특히 IRT는 몇 가지 이론적이고 검증 가능한 가정을 한다는 점에서 CTT와 다릅니다(Embretson &amp; Reise, 2000, 제1장 참조). 첫째, IRT는 피험자가 기저에 있는 잠재 특성의 수준에 따라 주어진 문항에 어떻게 반응하는지에 대한 확률적 모델입니다. 문항에 올바르게 응답하거나 더 일반적으로 문항을 지지할 확률은 측정된 잠재 특성(<span class="math inline">\(\theta\)</span>로 표시)의 단조 증가하는 함수입니다. 이 함수는 문항의 난이도(또는 위치), 변별도(또는 기울기), 추측도(즉, 낮은 점근값) 모수에 따라 달라질 수 있습니다. IRT와 달리 CTT는 문항과 측정된 잠재 특성 간의 관계보다는 관찰 가능한(즉, 원점수) 점수에만 초점을 맞춥니다.</p>
<p>둘째, IRT 모델에서 얻은 잠재 특성 추정치는 검사 문항 및 피험자 집단의 특성과 독립적인 것으로 가정하는 반면, CTT에서 얻은 검사 점수는 검사에서 선택한 문항에 크게 의존합니다. 문항의 난이도가 검사마다 다르더라도 IRT의 잠재 특성 추정치는 매우 유사할 것으로 예상되는 반면, CTT의 검사 점수는 검사에 따라 크게 다를 수 있습니다. 따라서 CTT 프레임워크에 비해 IRT 프레임워크 내에서 서로 다른 검사 간 피험자의 성적을 비교하는 것이 훨씬 쉽습니다.</p>
<p>셋째, IRT는 문항 모수가 피험자의 하위 그룹과 여러 검사 시행에 걸쳐 변하지 않는다고 가정합니다. 이러한 가정에 따라 문항은 피험자의 하위 그룹(예: 성별이나 인종이 다른 피험자)에 관계없이 동일한 모수를 가질 것으로 예상됩니다.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> 또한 문항 모수를 선형으로 변환할 수 있는 경우 여러 검사 시행에 걸친 문항은 상호 불변성으로 간주됩니다(Hambleton, Swaminathan, &amp; Rogers, 1991; Rupp &amp; Zumbo, 2006; Stocking &amp; Lord, 1983). IRT의 모수 불변성 속성을 통해 검사 동등화 및 컴퓨터 적응 검사에서 발생하는 문제와 같이 CTT에서 다루기 어려웠던 중요한 측정 문제를 해결할 수 있습니다(Hambleton et al., 1991).</p>
</section>
<section id="irt의-기본-개념" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="irt의-기본-개념"><span class="header-section-number">5.2.2</span> IRT의 기본 개념</h3>
<p>IRT 프레임워크 내에서 문항은 개별적으로 특성화되며, 문항에서 검사 특성이 도출됩니다. 이러한 특성에는 문항의 정답을 맞히는 데 필요한 잠재 특성 수준인 난이도<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, 잠재 특성 수준이 낮은 사람과 높은 사람을 구별하는 문항의 힘인 변별도, 잠재 특성 수준이 매우 낮은 수험자가 문항에 정답을 맞힐 확률인 추측도 등이 있습니다. 문항의 난이도, 변별도, 추측도 수준을 바탕으로 피험자의 잠재 특성(<span class="math inline">\(\theta\)</span>) 수준에 따라 문항을 정답으로 맞힐 확률을 나타내는 문항 특성 곡선(ICC)을 그릴 수 있습니다.</p>
<p>그림 5.1은 변별도와 추측도의 수준은 같지만 난이도(즉, 쉬움, 보통, 어려움)가 다른 세 문항의 ICC를 보여줍니다. 문항에 정답할 확률이 0.5가 되기 위해 필요한 잠재 특성 수준인 <span class="math inline">\(\theta\)</span>는 쉬운 문항의 경우 -1, 보통 문항의 경우 0, 어려운 문항의 경우 1입니다. ICC는 로지스틱 확률 곡선이기 때문에 잠재 특성은 일반적으로 -5에서 +5 범위의 로지스틱 척도에 있습니다. 문항의 난이도를 결정할 때도 동일한 로지스틱 척도가 사용됩니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_51.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">난이도가 각각 상, 중, 하인 문항의 문항특성곡선</figcaption><p></p>
</figure>
</div>
<p>그림 5.2는 난이도와 추측도 수준은 같지만 변별도 수준(즉, 낮음, 보통, 높음)이 다른 세 가지 문항의 ICC를 보여줍니다. 문항 변별도는 기본적으로 문항의 위치(난이도)에 따른 ICC의 기울기입니다(즉, 그림 5.2의 경우 <span class="math inline">\(\theta\)</span> = 0). ICC가 가파를수록 문항이 저능력 피험자와 고능력 피험자 간에 변별도가 높다는 것을 의미합니다. 그림 5.2에서 변별도가 가장 낮은 문항(점선)의 ICC가 가장 평탄한 기울기를 갖습니다. 다른 두 문항의 기울기가 높아질수록 문항의 변별도가 향상되고 해당 문항의 문항 위치에서 변별도가 더 높아집니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_52.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">변별도가 각각 상, 중, 하인 문항의 문항특성곡선</figcaption><p></p>
</figure>
</div>
<p>그림 5.3은 난이도와 변별도는 같지만 추측도의 수준(즉, 낮거나 높음)이 다른 두 문항의 ICC를 보여줍니다. 추측도의 수준이 높을수록 ICC의 절편(즉, ICC가 Y축과 교차하는 지점)이 증가합니다. 추측도의 수준이 높을수록 잠재 특성 수준이 낮은 피험자가 문항에 정답할 가능성이 높아집니다. 그림 5.3에서 추측도가 높은 문항(점선)의 ICC는 더 큰 절편으로, 잠재 특성 수준이 낮은 피험자(예: <span class="math inline">\(\theta\)</span> = -1)가 이 문항에 정답을 맞힐 확률이 약 60%에 달합니다. 추측도가 낮은 다른 문항(즉, 실선)의 경우 동일한 수험자가 해당 문항에 정답할 확률은 약 35%입니다. 추측도의 영향은 잠재 특성 수준이 증가함에 따라 감소합니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_53.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">추측도가 높고 낮은 문항의 문항 특성 곡선</figcaption><p></p>
</figure>
</div>
<p>IRT에서 또 다른 중요한 개념은 문항 정보 함수(IIF)입니다. IIF는 잠재 특성의 연속성을 따라 문항에 대한 정보의 양을 나타냅니다. 잠재 특성의 고정된 수준에 대해 IIF가 클수록 해당 잠재 특성의 특정 수준에서 피험자가 이용할 수 있는 정보가 많아집니다. 잠재 특성 수준 <span class="math inline">\(\theta\)</span>에서 문항 <span class="math inline">\(i\)</span>(<span class="math inline">\(i = 1, 2, …, N\)</span>)에 대한 정보 함수를 <span class="math inline">\(I_i(\theta)\)</span>로 표시합니다. 문항은 지역 독립성 가정이므로(아래 참조), 모든 문항에 대한 IIF를 합산하여 다음과 같이 검사 정보 함수(TIF)를 계산할 수 있습니다.</p>
<p><span class="math display">\[
I(\theta)=\sum_{i=1} ^N I_i(\theta)
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(I(\theta)\)</span>는 잠재 특성 <span class="math inline">\(\theta\)</span>에 대한 총 검사 정보입니다.</li>
</ul>
<p>TIF를 사용하면, 주어진 잠재 특성 수준에서 검사의 정밀도에 대한 정보를 제공하는 조건부 측정의 표준오차(cSEM)를 계산할 수 있습니다. cSEM 값은 다음에서 TIF의 역수 값의 제곱근입니다.</p>
<p><span class="math display">\[
cSEM(\theta)=\sqrt{1 \over I(\theta)^.}
\]</span></p>
<p>그림 5.4는 TIF(실선)와 cSEM(점선) 간의 상호 관계를 보여줍니다. TIF의 최대 지점은 cSEM의 최저 지점에 해당합니다. 즉, 검사 또는 문항에 대한 정보가 최대치에 있는 경우 이 지점 주변의 피험자에 대한 잠재 특성 수준을 더 정확하게 추정할 수 있습니다. 그림 5.4에서는 <span class="math inline">\(\theta\)</span>가 0에 가까운 피험자의 잠재 특성을 가장 정확하게 추정하는 검사임을 확인할 수 있습니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_54.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">TIF(실선)와 cSEM(점선) 간의 상호 관계</figcaption><p></p>
</figure>
</div>
<p>이로부터 얻을 수 있는 중요한 결론은 검사에 응시하는 피험자는 잠재 특성 수준에 따라 각기 다른 cSEM을 갖게 된다는 것입니다.</p>
</section>
<section id="irt-모델의-가정" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="irt-모델의-가정"><span class="header-section-number">5.2.3</span> IRT 모델의 가정</h3>
<p>IRT에는 두 가지 주요 모델링 가정이 있습니다. 하나는 단일 차원성과 지역 독립성입니다. 단일차원성 가정은 검사 문항 세트의 기저에 하나의 잠재 특성이 존재해야 한다는 가정입니다. 이 가정을 충족하려면 검사 수행에 영향을 미치는 지배적인 구성 요소 또는 요인을 찾아야 합니다. 단일 차원성 가정을 확인하는 방법에는 주성분 분석, 탐색적 요인 분석, 확인적 요인 분석, DIMTEST(Strout, 1990), DETECT(Zhang &amp; Stout, 1999) 등이 있습니다. 이러한 방법 중 탐색적 요인 분석과 확인적 요인 분석은 제4장에서 설명했습니다(차원성을 평가하는 가장 일반적인 방법).</p>
<p>지역 독립성 가정에 따르면 주어진 문항에 성공적으로 응답할 확률은 검사의 다른 문항에 대한 응답과 관계없이 잠재 특성에만 근거해야 합니다. 즉, 잠재 특성 수준에 따라 조건을 설정할 때 지역 독립성은 문항 간에 관계가 남아 있지 않음을 의미합니다(Embretson &amp; Reise, 2000). 단일 차원성 가정이 성립하면 두 개념이 하나의 잠재 특성을 통해서만 서로 관련되기 때문에 지역 독립성 가정도 충족됩니다(Lord, 1980). Yen의 Q3 통계(Yen, 1984)는 지역 독립성 가정을 검증하는 데 가장 일반적으로 사용되는 방법 중 하나입니다.</p>
<p>검사 문항의 단일 차원성 및 지역 독립성 외에도 문항 모수와 잠재 특성 수준을 추정하기 전에 확인해야 할 몇 가지 가정이 있습니다. 비속도 검사 시행 가정에서는 모든 피험자가 검사 문항에 답할 수 있는 충분한 시간을 가져야 합니다. Rasch, 1모수 및 2모수 IRT 모델에서는 주어진 문항에 대한 정답을 추측하는 것이 해당 문항의 정답 확률에 미치는 영향이 미미하거나 전혀 없다고 가정합니다. 이 가정에 따르면 1모수 및 2모수 모델의 ICC는 0에 낮은 점근값을 갖습니다. 이 가정은 잠재 특성 수준이 낮은 피험자가 해당 문항에 정답할 확률이 매우 낮다는 것을 나타냅니다. 마지막 가정은 문항 변별도가 검사의 모든 문항에서 동일하다는 가정이며, 이는 Rasch 및 1모수 IRT 모델에서만 가정됩니다. 이 가정은 모든 문항에서 문항 변별도가 동일(즉, “1” 또는 다른 추정 값)하도록 제한합니다.</p>
</section>
</section>
<section id="이분-문항에-대한-단일-차원-irt-모델" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="이분-문항에-대한-단일-차원-irt-모델"><span class="header-section-number">5.3</span> 이분 문항에 대한 단일 차원 IRT 모델</h2>
<p>이분으로 채점된 검사 문항에 대한 4개의 단일 차원 IRT 모델에는 1모수, 2모수, 3모수 및 4모수 IRT 모델이 있습니다.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> 이러한 모델은 변별도와 추측도에 대한 가정과 모델링 제약 조건에 따라 다릅니다.</p>
<section id="모수-로지스틱-모델과-rasch-모델" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="모수-로지스틱-모델과-rasch-모델"><span class="header-section-number">5.3.1</span> 1모수 로지스틱 모델과 Rasch 모델</h3>
<section id="모수-로지스틱-모델" class="level4" data-number="5.3.1.1">
<h4 data-number="5.3.1.1" class="anchored" data-anchor-id="모수-로지스틱-모델"><span class="header-section-number">5.3.1.1</span> 1모수 로지스틱 모델</h4>
<p>가장 간단한 IRT 모델은 1모수 로지스틱 IRT 모델(1PL 모델이라고도 함)입니다. 수학적으로 1PL 모델은 다음과 같이 작성할 수 있습니다.</p>
<p><span class="math display">\[
P(Y_{ij}=1|\theta_j, a, b_i) = {exp(Da(\theta_j-b_i)) \over 1+exp(Da(\theta_j-b_i))}
\]</span></p>
<ul>
<li><p>여기서 <span class="math inline">\(\theta_j\)</span>는 피험자 <span class="math inline">\(j\)</span>의 잠재 특성 수준(<span class="math inline">\(j = 1, …, J\)</span>),</p></li>
<li><p><span class="math inline">\(a\)</span>는 문항 변별도 모수,</p></li>
<li><p><span class="math inline">\(b_i\)</span>는 문항 <span class="math inline">\(i\)</span>의 문항 난이도 모수(<span class="math inline">\(i = 1, …, I\)</span>),</p></li>
<li><p><span class="math inline">\(D\)</span>는 로지스틱 모델의 모수를 정규 오자이브 모델의 척도에 배치하는 척도 상수입니다(<span class="math inline">\(D = 1.7\)</span>일 때).</p></li>
</ul>
<p>이 방정식은 피험자 <span class="math inline">\(j\)</span>가 문항 <span class="math inline">\(i\)</span>에 정답할 확률이 잠재 특성, 문항 변별도 및 문항 난이도의 함수임을 나타냅니다. 방정식 5.3에서 문항 변별도에 대한 첨자가 없고 추측도에 대한 언급이 없는 것을 알 수 있습니다. 이는 1PL 모델에서는 문항 변별도가 동일하고 추측도가 문항에 정답하는 데 미치는 영향이 없다고 가정한다는 것을 나타냅니다.</p>
<p>R에서 1PL 모델을 추정하는 방법을 보여주기 위해 제2장에서 소개한 hemp 패키지에 포함된 SAPA 데이터 세트를 다시 고려합니다. 문항 모수를 추정하기 위해 mirt 패키지의 mirt 함수를 사용합니다(Chalmers, 2012). mirt 패키지의 함수를 사용하려면 먼저 mirt 패키지를 설치해야 합니다. 그런 다음 라이브러리 명령을 사용하여 mirt와 hemp를 모두 활성화합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("mirt")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mirt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: stats4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"hemp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: psych</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lavaan</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-16
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lavaan'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:psych':

    cor2cov</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lme4'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:mirt':

    fixef</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: reshape2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: boot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'boot'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:psych':

    logit</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:lattice':

    melanoma</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: equate</code></pre>
</div>
</div>
<p>SAPA 데이터 세트에 대해 mirt에서 1PL 모델을 정의하려면 mirt의 모델 구문을 사용하여 onepl_mod로 저장합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>onepl_mod <span class="ot">&lt;-</span> <span class="st">"F = 1 - 16</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="st">CONSTRAIN = (1 - 16, a1)"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>이 코드의 첫 번째 줄은 SAPA 데이터 세트의 열 1~16에 있는 문항에 의해 단일 잠재 특성 F가 나타난다는 것을 나타냅니다. CONSTRAIN으로 시작하는 두 번째 줄은 열 1부터 16까지의 문항이 동일한 문항 변별도를 갖도록 제한합니다. mirt 패키지는 방정식 5.3에 표시된 것처럼 단일 차원 IRT 모델의 문항 변별도 모수를 a가 아닌 a1으로 레이블을 지정합니다. 1PL을 1 ~ 4열의 문항에만 맞추려면 1 - 16을 1 - 4로 변경하고, 1 ~ 3열, 5열, 9 ~ 16열의 문항을 사용하려면 1 - 3, 5, 9~16으로 정의하면 됩니다.</p>
<p>mirt 패키지의 구문은 처음에는 조금 번거롭고 어려울 수 있습니다. 하지만 이 패키지는 다양한 IRT 모델(예: 다분 IRT 모델, 다차원 IRT 모델, 설명적 IRT 모델)<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>을 추정할 수 있으므로 IRT 모델 추정을 위해 이 패키지를 학습하는 것을 적극 권장합니다.</p>
<p>다음으로, 위에서 정의한 모델을 사용하여 1PL 모델에 적합하고 SE = TRUE를 설정하여 문항 모수에 대한 표준 오차를 추정하도록 mirt 함수에 지시합니다. 적합된 모델을 onepl_fit에 저장합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>onepl_fit <span class="ot">&lt;-</span> <span class="fu">mirt</span>(<span class="at">data =</span> SAPA, <span class="at">model =</span> onepl_mod, <span class="at">SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Iteration: 1, Log-Lik: -13494.679, Max-Change: 0.23406
Iteration: 2, Log-Lik: -13335.854, Max-Change: 0.12756
Iteration: 3, Log-Lik: -13292.524, Max-Change: 0.07878
Iteration: 4, Log-Lik: -13277.030, Max-Change: 0.05217
Iteration: 5, Log-Lik: -13270.789, Max-Change: 0.03431
Iteration: 6, Log-Lik: -13268.209, Max-Change: 0.02244
Iteration: 7, Log-Lik: -13266.529, Max-Change: 0.00847
Iteration: 8, Log-Lik: -13266.376, Max-Change: 0.00575
Iteration: 9, Log-Lik: -13266.308, Max-Change: 0.00382
Iteration: 10, Log-Lik: -13266.259, Max-Change: 0.00131
Iteration: 11, Log-Lik: -13266.255, Max-Change: 0.00084
Iteration: 12, Log-Lik: -13266.253, Max-Change: 0.00062
Iteration: 13, Log-Lik: -13266.251, Max-Change: 0.00017
Iteration: 14, Log-Lik: -13266.251, Max-Change: 0.00013
Iteration: 15, Log-Lik: -13266.251, Max-Change: 0.00009

Calculating information matrix...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>onepl_params <span class="ot">&lt;-</span> <span class="fu">coef</span>(onepl_fit, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>onepl_fit 개체에는 추정된 문항 모수, 잠재 특성의 평균, 잠재 특성의 분산-공분산 행렬 및 추정 프로세스와 관련된 추가 정보가 포함되어 있습니다. 모델 적합 후 추정된 모수와 잠재 특성의 평균 및 공분산 행렬을 coef 함수를 사용하여 추출하고 이를 onepl_params에 저장합니다. 이 단계에서 IRTpars = TRUE를 사용하여 기울기 및 절편 모수(mirt의 기본 모수화)를 기존 IRT 모수로 변환하고, simplify = TRUE를 사용하여 문항 모수를 긴 목록이 아닌 단일 데이터 프레임으로 결합했습니다. 절편 모수를 기존 문항 난이도 모수로 변환하는 방법은 다음 공식을 사용하여 수행할 수 있습니다.</p>
<p><span class="math display">\[
b_i={-d_i \over a1_i}
\]</span></p>
<ul>
<li><p>여기서 <span class="math inline">\(d_i\)</span>는 절편 모수,</p></li>
<li><p><span class="math inline">\(a1_i\)</span>는 기울기(즉, 변별도) 모수,</p></li>
<li><p><span class="math inline">\(b_i\)</span>는 기존의 문항 난이도 모수입니다.</p></li>
</ul>
<p><span class="math inline">\(d_i\)</span>와 <span class="math inline">\(b_i\)</span>의 주요 차이점은 <span class="math inline">\(b_i\)</span>는 문항 난이도를 나타내는 반면, <span class="math inline">\(d_i\)</span>는 문항 쉬움을 나타낸다는 점입니다.</p>
<p>마지막으로, 추정된 문항 모수를 보다 간결하게 출력하기 위해 문항이 포함된 데이터 프레임을 onepl_items에 저장하고 head 함수를 사용하여 처음 6행을 확인합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>onepl_items <span class="ot">&lt;-</span> onepl_params<span class="sc">$</span>items</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(onepl_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 a          b g u
reason.4  1.445587 -0.5557199 0 1
reason.16 1.445587 -0.8020747 0 1
reason.17 1.445587 -0.7980649 0 1
reason.19 1.445587 -0.4546611 0 1
letter.7  1.445587 -0.3923381 0 1
letter.33 1.445587 -0.2810892 0 1</code></pre>
</div>
</div>
<p>각 행은 문항 이름으로 시작하며 열은 추정된 문항 모수에 해당합니다. 첫 번째 열(a)은 문항 변별도, 두 번째 열(b)은 문항 난이도, 세 번째 열(g)은 하부 점근값(즉, 추측도), 마지막 열(u)은 상부 점근값입니다. 1PL 모델에는 하한 및 상한 점근 모수가 포함되지 않으므로 마지막 두 열은 항상 각각 0과 1이 되므로 무시합니다. (하한 및 상한 점근 모수에 대한 자세한 내용은 3PL 및 4PL 모델 섹션의 뒷부분에서 설명합니다.) 첫 번째 열에는 1.446으로 추정된 문항 판별도 모수가 표시됩니다. 1PL 모델을 사용했기 때문에 문항 판별도 모수는 모든 문항에서 동일합니다. 두 번째 열에는 추정된 문항 난이도 모수가 표시됩니다. SAPA 데이터 세트에서 두 번째 문항(reason.16)은 가장 쉬운 문항이고 마지막 문항(rotate. 8)은 검사에서 가장 어려운 문항입니다.</p>
<p>추정된 문항 모수에 대한 표준 오차를 확인하려면 printSE = TRUE 인수를 사용하여 coef 함수를 다시 실행해야 합니다. 아래에서 이 작업을 수행하고 name 함수를 사용하여 출력 내용을 인쇄합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>onepl_se <span class="ot">&lt;-</span> <span class="fu">coef</span>(onepl_fit, <span class="at">printSE =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(onepl_se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "reason.4"  "reason.16" "reason.17" "reason.19" "letter.7"  "letter.33"
 [7] "letter.34" "letter.58" "matrix.45" "matrix.46" "matrix.47" "matrix.55"
[13] "rotate.3"  "rotate.4"  "rotate.6"  "rotate.8"  "GroupPars"</code></pre>
</div>
</div>
<p>onepl_se 개체는 각 문항에 대한 정보를 개별적으로 포함하는 목록이라는 것을 알 수 있습니다. 가장 어려운 문항인 rotate.8에 대한 정보를 보려면 아래와 같이 $ 기호를 사용하여 추출할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>onepl_se<span class="sc">$</span>rotate<span class="fl">.8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            a1           d logit(g) logit(u)
par 1.44558726 -2.00517306     -999      999
SE  0.03612038  0.08517212       NA       NA</code></pre>
</div>
</div>
<p>첫 번째 행은 추정된 모수에 해당하고 두 번째 행은 표준 오차에 해당합니다. 첫 번째 열은 다시 문항 변별도에 해당하지만 두 번째 열은 더 이상 문항 난이도에 해당하지 않습니다(이제 b가 d가 됨). 문항 난이도에 대한 표준 오차가 필요한 독자의 경우 ltm 패키지(Rizopoulos, 2006)에서 이 정보를 제공합니다. -999, 999 및 NA는 모델에 대해 하한 및 상한 점근 모수가 추정되지 않았기 때문입니다.</p>
<p>mirt 패키지는 다양한 문항 및 검사 특성을 나타내는 그래프에 대한 두 가지 함수, plot과 itemplot을 제공합니다. 이 함수는 사실 lattice 패키지의 xyplot 함수를 위한 래퍼 함수일 뿐입니다. 따라서 그래프를 사용자화하려면 xyplot 함수에 사용할 수 있는 모든 그래픽 인수(예: 색상 또는 선 유형 변경)를 사용할 수 있습니다(자세한 내용은 ?xyplot 참조).</p>
<p>아래 예는 처음 두 문항에 대한 ICC를 만드는 방법을 보여줍니다. 그림 5.5에서 ICC의 x축은 잠재 특성(<span class="math inline">\(\theta\)</span>)을 나타내며, SAPA 데이터 세트의 경우 지능 또는 적성으로 간주될 수 있고, ICC의 y축은 해당 문항에 정답할 확률인 <span class="math inline">\(P(\theta)\)</span>를 나타냅니다. 1PL 모델은 변별도 모수가 모든 문항에서 동일하도록 제약하기 때문에 ICC의 기울기는 동일하지만 문항 난이도 모수는 X축을 따라 이동합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>위에 제시된 코드를 실행하면 그래프는 컬러로 표시되지만 여기서는 회색조로 표시된다는 점을 독자들에게 상기시키고자 합니다.</p>
<p>ICC를 만드는 다른 방법은 itemplot 함수를 사용하는 것입니다. 다음 예제에서는 처음 두 문항에 itemplot 함수를 다시 사용합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemplot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">item =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemplot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">item =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>잠재 특성의 함수로 문항 정보의 양을 표시하는 문항 정보 그래프도 plot 함수를 사용하여 쉽게 만들 수 있습니다. 아래에서는 SAPA 데이터 세트의 세 번째 및 다섯 번째 문항에 대한 IIF를 그리는 방법을 보여줍니다(그림 5.6 참조).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"infotrace"</span>, <span class="at">which.items =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>그림 5.5와 그림 5.6에서는 문항에 대해 ICC와 IIF가 개별적으로 그려져 있습니다. facet_items = FALSE 인수를 사용하여 단일 그래프 내에서 두 문항의 그래프를 결합할 수 있습니다. 다음 예에서는 문항 1과 2의 ICC 그래프를 함께 결합합니다. 또한 auto.key = list(points = FALSE, lines = TRUE, columns = 2) 및 par.settings = simpleTheme(lty = 1:2)를 설정하여 각 ICC의 선 유형을 구분하고 문항을 나타내는 두 열 범례를 그립니다. 그림 5.7은 문항 1(실선)과 문항 2(점선)에 대한 결합된 ICC를 보여줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">facet_items =</span> <span class="cn">FALSE</span>, <span class="at">auto.key =</span> <span class="fu">list</span>(<span class="at">points =</span> <span class="cn">FALSE</span>, <span class="at">lines =</span> <span class="cn">TRUE</span>, <span class="at">columns =</span> <span class="dv">2</span>), </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">par.settings =</span> <span class="fu">simpleTheme</span>(<span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>ICC 및 IIF 외에도 TIF 그래프와 cSEM 그래프를 만들 수도 있습니다. 다음 예에서는 능력 범위(-3 ~ 3)를 지정하고 1PL SAPA 모델에 대해 결합된 TIF 및 cSEM 그래프를 만드는 방법을 보여 줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"infoSE"</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>그림 5.8은 SAPA 데이터 세트의 문항이 매우 유익하며 <span class="math inline">\(\theta\)</span> = -1 에서 <span class="math inline">\(\theta\)</span> = 1 사이의 측정 오차가 가장 적다는 것을 보여줍니다. 또한 plot 함수의 type = “info” 및 type = “SE” 인수를 사용하여 별도의 TIF 및 cSEM 그래프를 만들 수도 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"info"</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(onepl_fit, <span class="at">type =</span> <span class="st">"SE"</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="rasch-모델" class="level4" data-number="5.3.1.2">
<h4 data-number="5.3.1.2" class="anchored" data-anchor-id="rasch-모델"><span class="header-section-number">5.3.1.2</span> Rasch 모델</h4>
<p>Rasch 모델(Rasch, 1960)은 모든 문항에 대해 문항 변별도가 1로 설정된 1PL 모델의 특정 형태입니다. 이러한 조정의 결과로 문항에 정답할 확률은 문항의 난이도와 잠재 특성만 고려한 함수가 됩니다. 수학적으로 Rasch 모델은 다음과 같이 작성할 수 있습니다.</p>
<p><span class="math display">\[
P(Y_{ij}=1|\theta_j, b_i) = {exp(D(\theta_j-b_i)) \over 1+exp(D(\theta_j-b_i))}
\]</span></p>
<p>여기서 모든 구성 요소는 공통 문항 변별도 모수를 제외한 모든 구성 요소가 1PL 모델과 동일하며, 모든 문항에 대해 a = 1이므로 생략할 수 있습니다.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>문항 변별도 모수는 문항의 정답 확률에 영향을 미치지 않으므로 간단한 설명을 통해 문항 난이도와 잠재 특성 간의 관계를 설명할 수 있습니다. 피험자의 잠재 특성 수준이 문항의 난이도와 일치하는 경우, 피험자는 해당 문항을 정답으로 맞힐 확률이 50%입니다(추측도가 포함되지 않았다고 가정할 경우). Rasch 모델에서는 어떤 문항 난이도 위치를 사용했는지에 관계없이 피험자의 예상 응답 순서가 동일하게 정해집니다. 마찬가지로, 문항은 어떤 수준의 잠재 특성을 고려하든 예측된 응답의 측면에서 동일하게 정렬됩니다.</p>
<p>Rasch 모델을 설명하기 위해 다시 SAPA 데이터 세트를 사용합니다. 1PL 모델과 달리 Rasch 모델 구문에는 CONSTRAIN 명령이 필요하지 않습니다. 대신 mirt 함수에 itemtype = “Rasch”를 지정하여 Rasch 모델에 따라 문항 모수를 추정하고 적합 모델을 rasch_fit에 저장합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>rasch_mod <span class="ot">&lt;-</span> <span class="st">"F = 1 - 16"</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>rasch_fit <span class="ot">&lt;-</span> <span class="fu">mirt</span>(<span class="at">data =</span> SAPA, <span class="at">model =</span> rasch_mod, </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">itemtype =</span> <span class="st">"Rasch"</span>, <span class="at">SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Iteration: 1, Log-Lik: -13381.676, Max-Change: 0.37122
Iteration: 2, Log-Lik: -13304.782, Max-Change: 0.28795
Iteration: 3, Log-Lik: -13277.916, Max-Change: 0.18828
Iteration: 4, Log-Lik: -13269.602, Max-Change: 0.11075
Iteration: 5, Log-Lik: -13267.193, Max-Change: 0.06135
Iteration: 6, Log-Lik: -13266.517, Max-Change: 0.03290
Iteration: 7, Log-Lik: -13266.327, Max-Change: 0.01775
Iteration: 8, Log-Lik: -13266.276, Max-Change: 0.00886
Iteration: 9, Log-Lik: -13266.262, Max-Change: 0.00459
Iteration: 10, Log-Lik: -13266.257, Max-Change: 0.00243
Iteration: 11, Log-Lik: -13266.256, Max-Change: 0.00120
Iteration: 12, Log-Lik: -13266.255, Max-Change: 0.00063
Iteration: 13, Log-Lik: -13266.255, Max-Change: 0.00034
Iteration: 14, Log-Lik: -13266.255, Max-Change: 0.00016
Iteration: 15, Log-Lik: -13266.255, Max-Change: 0.00009

Calculating information matrix...</code></pre>
</div>
</div>
<p>앞서 1PL 모델에 대해 수행한 것처럼 coef 함수를 사용하여 추정된 문항 모수를 추출하고, 이를 저장하고(rasch_params), 문항 모수를 데이터 프레임으로 추출한 다음(rasch_items), 마지막으로 head 함수를 사용하여 처음 6개의 행을 출력할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>rasch_params <span class="ot">&lt;-</span> <span class="fu">coef</span>(rasch_fit, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>rasch_items <span class="ot">&lt;-</span> rasch_params<span class="sc">$</span>items</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rasch_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          a          b g u
reason.4  1 -0.8024508 0 1
reason.16 1 -1.1585583 0 1
reason.17 1 -1.1527651 0 1
reason.19 1 -0.6563678 0 1
letter.7  1 -0.5662859 0 1
letter.33 1 -0.4054796 0 1</code></pre>
</div>
</div>
<p>결과에서 첫 번째 열(즉, 문항 변별도)은 Rasch 모델의 모든 문항에 대해 1이지만, 1PL 모델의 모든 문항에 대해 문항 변별도는 1.446으로 추정되었습니다. 두 번째 열은 문항 변별도 외에도 Rasch 모델의 문항 난이도 모수가 1PL 모델의 문항 난이도 모수와 다르다는 것을 나타냅니다.</p>
<p>1PL과 마찬가지로 Rasch 모델에 대한 ICC를 그래프로 그릴 수 있습니다. Rasch 모델의 결과에 따르면, 문항 2(reason.16)가 가장 쉬운 문항이고 문항 16(rotate.8)이 SAPA 데이터 세트에서 가장 어려운 문항입니다. 이는 1PL 모델에서 가장 쉬운 문항과 가장 어려운 문항으로 식별된 것과 동일한 문항입니다. 아래에는 이 두 문항에 대한 ICC가 표시되어 있습니다(그림 5.9 참조).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rasch_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">16</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Rasch 모델은 모든 문항에 대해 문항 변별도 모수가 1이라고 가정하기 때문에 그림 5.5에 제시된 것보다 그림 5.9의 ICC가 덜 가파르다는 점에 유의하십시오. 그림 5.9는 잠재 특성에서 낮은 능력을 가진 피험자도 문항 2를 정답으로 맞힐 확률이 높은 반면, 문항 16은 적어도 <span class="math inline">\(\theta = 2\)</span> 이상의 높은 능력을 가진 피험자만 정답으로 맞힐 확률이 50%라는 것을 보여줍니다. 1PL 모델에 대해 설명한 것처럼 Rasch 모델에 대해서도 유사한 방식으로 IIF와 TIF를 생성할 수 있습니다. 독자들이 연습할 수 있도록 남겨두겠습니다.</p>
</section>
</section>
<section id="모수-로지스틱-모델-1" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="모수-로지스틱-모델-1"><span class="header-section-number">5.3.2</span> 2모수 로지스틱 모델</h3>
<p>2모수 로지스틱(2PL) 모델은 1PL 및 Rasch 모델보다 유연한 형태입니다. 2PL 모델에서는 각 문항이 고유한 문항 변별도 모수를 가질 수 있습니다. 2PL 모델의 수학적 공식은 다음과 같습니다.</p>
<p><span class="math display">\[
P(Y_{ij}=1|\theta_j, a_i, b_i) = {exp(Da_i(\theta_j-b_i)) \over 1+exp(Da_i(\theta_j-b_i))}
\]</span></p>
<p>여기서 모수는 위 방정식 5.3에 대해 설명한 것과 동일하지만 <span class="math inline">\(a_i\)</span>가 문항 <span class="math inline">\(i\)</span>에 대한 유일한 변별도 모수라는 점을 제외하면 동일합니다.</p>
<p>다음 예에서는 2PL 모델을 사용하여 SAPA 데이터 세트의 문항 모수를 추정합니다. 2PL 모델을 추정하는 모델 구문은 Rasch 모델과 동일한 방식입니다. 유일한 차이점은 mirt 함수를 호출할 때입니다. 이번에는 2PL 모델을 추정하기 위해 itemtype = “2PL” 인수를 전달해야 합니다. 이전과 마찬가지로, 적합 모델을 저장하고(twopl_fit), 모델 모수를 추출하고(twopl_params), 모든 문항에 대한 문항 모수를 출력합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>twopl_mod <span class="ot">&lt;-</span> <span class="st">"F = 1 - 16"</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>twopl_fit <span class="ot">&lt;-</span> <span class="fu">mirt</span>(<span class="at">data =</span> SAPA, <span class="at">model =</span> twopl_mod, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">itemtype =</span> <span class="st">"2PL"</span>, <span class="at">SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Iteration: 1, Log-Lik: -13494.679, Max-Change: 0.53899
Iteration: 2, Log-Lik: -13284.214, Max-Change: 0.25237
Iteration: 3, Log-Lik: -13231.691, Max-Change: 0.16517
Iteration: 4, Log-Lik: -13213.028, Max-Change: 0.10162
Iteration: 5, Log-Lik: -13205.997, Max-Change: 0.07336
Iteration: 6, Log-Lik: -13202.832, Max-Change: 0.04558
Iteration: 7, Log-Lik: -13201.628, Max-Change: 0.02752
Iteration: 8, Log-Lik: -13200.891, Max-Change: 0.02268
Iteration: 9, Log-Lik: -13200.619, Max-Change: 0.01424
Iteration: 10, Log-Lik: -13200.449, Max-Change: 0.00438
Iteration: 11, Log-Lik: -13200.420, Max-Change: 0.00306
Iteration: 12, Log-Lik: -13200.407, Max-Change: 0.00227
Iteration: 13, Log-Lik: -13200.397, Max-Change: 0.00068
Iteration: 14, Log-Lik: -13200.397, Max-Change: 0.00031
Iteration: 15, Log-Lik: -13200.397, Max-Change: 0.00083
Iteration: 16, Log-Lik: -13200.396, Max-Change: 0.00032
Iteration: 17, Log-Lik: -13200.396, Max-Change: 0.00072
Iteration: 18, Log-Lik: -13200.396, Max-Change: 0.00027
Iteration: 19, Log-Lik: -13200.396, Max-Change: 0.00024
Iteration: 20, Log-Lik: -13200.396, Max-Change: 0.00012
Iteration: 21, Log-Lik: -13200.396, Max-Change: 0.00032
Iteration: 22, Log-Lik: -13200.396, Max-Change: 0.00013
Iteration: 23, Log-Lik: -13200.396, Max-Change: 0.00029
Iteration: 24, Log-Lik: -13200.396, Max-Change: 0.00011
Iteration: 25, Log-Lik: -13200.396, Max-Change: 0.00009

Calculating information matrix...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>twopl_params <span class="ot">&lt;-</span> <span class="fu">coef</span>(twopl_fit, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>twopl_items <span class="ot">&lt;-</span> twopl_params<span class="sc">$</span>items</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>twopl_items</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  a          b g u
reason.4  1.6924256 -0.5127258 0 1
reason.16 1.4616058 -0.7967194 0 1
reason.17 1.8568189 -0.7052519 0 1
reason.19 1.4429276 -0.4544282 0 1
letter.7  1.5739581 -0.3749607 0 1
letter.33 1.3512472 -0.2906578 0 1
letter.34 1.6568903 -0.4165187 0 1
letter.58 1.4637541  0.2090402 0 1
matrix.45 1.0649705 -0.1241352 0 1
matrix.46 1.1060157 -0.2292152 0 1
matrix.47 1.3463316 -0.4666121 0 1
matrix.55 0.8786048  0.6793708 0 1
rotate.3  1.7878172  1.1986461 0 1
rotate.4  2.0841977  1.0317428 0 1
rotate.6  1.6388551  0.7524753 0 1
rotate.8  1.5855260  1.3201267 0 1</code></pre>
</div>
</div>
<p>2PL 모델의 결과에서 문항 변별도(첫 번째 열)와 난이도(두 번째 열) 모수는 각 문항마다 다릅니다. item 14(rotate.4)의 문항 변별도가 가장 높은 반면(2.084), item 12(matrix.55)의 문항 변별도가 가장 낮습니다. 다음으로, plot 함수를 사용하여 ICC 그래프로 이 두 문항의 차이를 시각적으로 살펴봅니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(twopl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>그림 5.10은 문항 변별도 모수의 차이로 인해 rotate.4(오른쪽)의 기울기가 matrix.55(왼쪽)의 기울기보다 훨씬 가파르다는 것을 보여줍니다. 이 차이는 2PL 모델을 사용하여 문항 모수를 추정할 때 item 14(rotate.4)가 item 12(matrix.55)보다 잠재 특성이 낮은 피험자와 높은 피험자를 더 잘 구분할 수 있음을 시사합니다.</p>
<p>또한 난이도 모수는 다르지만 변별도가 비슷한 문항에 대한 ICC를 비교할 수도 있습니다. 예를 들어, SAPA 데이터 세트에서 item 5(letter.7)와 item 16(rotate.8)은 문항 변별도 모수가 비슷하지만 난이도 측면에서 차이가 있습니다. 아래 표시된 코드를 사용하여 생성된 그림 5.11은 추정된 잠재 특성 수준 <span class="math inline">\(\theta = 0\)</span>에서 letter.7(더 쉬운 문항)을 정답할 확률은 거의 0.7이지만 rotate.8(더 어려운 문항)을 정답할 확률은 0.1에 불과하다는 것을 보여줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(twopl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">16</span>),</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">facet_items =</span> <span class="cn">FALSE</span>, </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">auto.key =</span> <span class="fu">list</span>(<span class="at">points =</span> <span class="cn">FALSE</span>, </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lines =</span> <span class="cn">TRUE</span>, <span class="at">columns =</span> <span class="dv">2</span>), </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">par.settings =</span> <span class="fu">simpleTheme</span>(<span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="모수-로지스틱-모델-2" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="모수-로지스틱-모델-2"><span class="header-section-number">5.3.3</span> 3모수 로지스틱 모델</h3>
<p>3모수 로지스틱(3PL) 모델은 2PL 모델의 확장에 불과합니다. 이 모델에는 2PL 모델과 동일한 문항 모수(예: <span class="math inline">\(a_i\)</span> 및 <span class="math inline">\(b_i\)</span>)와 우연 또는 추측만으로 문항을 지지할 가능성을 나타내는 추가 모수(<span class="math inline">\(c_i\)</span>)가 포함됩니다. <span class="math inline">\(c_i\)</span> 모수는 하부 점근 또는 의사 추측도 모수라고 합니다. 3PL 모델은 다음과 같이 작성할 수 있습니다.</p>
<p><span class="math display">\[
P(Y_{ij}=1|\theta_j, a_i, b_i, c_i) = c_i + {1-c_i \over 1+exp(-Da_i(\theta_j-b_i))}
\]</span></p>
<p>Rasch, 1PL 및 2PL 모델과 달리 3PL 모델에서의 정답 확률은 잠재 특성이 <span class="math inline">\(-\infty\)</span>로 이동함에 따라 0에 가까워지지 않습니다. 대신 확률은 양수 값에 가까워집니다(일반적으로 <span class="math inline">\(1/k\)</span>, 여기서 <span class="math inline">\(k\)</span>는 선다형 문항의 반응 범주 수). <span class="math inline">\(c_i\)</span> 모수를 포함하는 이유는 잠재 특성이 매우 낮은 일부 피험자는 응답 옵션을 무작위로 선택할 가능성이 높기 때문에 무작위 추측을 하면 <span class="math inline">\(c_i\)</span>와 같은 확률로 정답을 선택할 수 있기 때문입니다.</p>
<p>다음 예에서는 3PL 모델을 사용하여 SAPA 데이터 세트에 대한 문항 모수를 추정합니다. 모델을 맞출 때 itemtype = “3PL” 인수를 지정하여 3PL 모델을 추정합니다. 아래에서는 적합 모델을 정의, 적합 및 저장하고, 모수를 추출하고, 문항 모수의 처음 몇 행을 출력합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>threepl_mod <span class="ot">&lt;-</span> <span class="st">"F = 1-16"</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>threepl_fit <span class="ot">&lt;-</span> <span class="fu">mirt</span>(<span class="at">data =</span> SAPA, <span class="at">model =</span> threepl_mod, </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">itemtype =</span> <span class="st">"3PL"</span>, <span class="at">SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Iteration: 1, Log-Lik: -13980.085, Max-Change: 3.07860
Iteration: 2, Log-Lik: -13349.993, Max-Change: 1.58321
Iteration: 3, Log-Lik: -13250.082, Max-Change: 0.63745
Iteration: 4, Log-Lik: -13193.936, Max-Change: 0.60611
Iteration: 5, Log-Lik: -13162.424, Max-Change: 0.46102
Iteration: 6, Log-Lik: -13145.533, Max-Change: 0.46319
Iteration: 7, Log-Lik: -13135.526, Max-Change: 0.43833
Iteration: 8, Log-Lik: -13129.722, Max-Change: 0.39049
Iteration: 9, Log-Lik: -13126.097, Max-Change: 0.23341
Iteration: 10, Log-Lik: -13123.127, Max-Change: 0.11726
Iteration: 11, Log-Lik: -13121.920, Max-Change: 0.10081
Iteration: 12, Log-Lik: -13121.459, Max-Change: 1.08910
Iteration: 13, Log-Lik: -13120.941, Max-Change: 0.09246
Iteration: 14, Log-Lik: -13120.755, Max-Change: 0.28264
Iteration: 15, Log-Lik: -13120.632, Max-Change: 0.06058
Iteration: 16, Log-Lik: -13120.609, Max-Change: 0.02914
Iteration: 17, Log-Lik: -13120.555, Max-Change: 0.02525
Iteration: 18, Log-Lik: -13120.515, Max-Change: 0.00717
Iteration: 19, Log-Lik: -13120.508, Max-Change: 0.00664
Iteration: 20, Log-Lik: -13120.464, Max-Change: 0.02348
Iteration: 21, Log-Lik: -13120.442, Max-Change: 0.00521
Iteration: 22, Log-Lik: -13120.440, Max-Change: 0.00508
Iteration: 23, Log-Lik: -13120.428, Max-Change: 0.00501
Iteration: 24, Log-Lik: -13120.413, Max-Change: 0.00326
Iteration: 25, Log-Lik: -13120.405, Max-Change: 0.00246
Iteration: 26, Log-Lik: -13120.400, Max-Change: 0.00239
Iteration: 27, Log-Lik: -13120.395, Max-Change: 0.00315
Iteration: 28, Log-Lik: -13120.385, Max-Change: 0.00138
Iteration: 29, Log-Lik: -13120.382, Max-Change: 0.00119
Iteration: 30, Log-Lik: -13120.381, Max-Change: 0.00105
Iteration: 31, Log-Lik: -13120.378, Max-Change: 0.00225
Iteration: 32, Log-Lik: -13120.377, Max-Change: 0.00108
Iteration: 33, Log-Lik: -13120.376, Max-Change: 0.00133
Iteration: 34, Log-Lik: -13120.375, Max-Change: 0.00064
Iteration: 35, Log-Lik: -13120.374, Max-Change: 0.00069
Iteration: 36, Log-Lik: -13120.374, Max-Change: 0.00061
Iteration: 37, Log-Lik: -13120.374, Max-Change: 0.00135
Iteration: 38, Log-Lik: -13120.374, Max-Change: 0.00035
Iteration: 39, Log-Lik: -13120.374, Max-Change: 0.00084
Iteration: 40, Log-Lik: -13120.373, Max-Change: 0.00047
Iteration: 41, Log-Lik: -13120.373, Max-Change: 0.00122
Iteration: 42, Log-Lik: -13120.373, Max-Change: 0.00033
Iteration: 43, Log-Lik: -13120.373, Max-Change: 0.00029
Iteration: 44, Log-Lik: -13120.373, Max-Change: 0.00071
Iteration: 45, Log-Lik: -13120.373, Max-Change: 0.00116
Iteration: 46, Log-Lik: -13120.373, Max-Change: 0.00077
Iteration: 47, Log-Lik: -13120.373, Max-Change: 0.00024
Iteration: 48, Log-Lik: -13120.373, Max-Change: 0.00064
Iteration: 49, Log-Lik: -13120.373, Max-Change: 0.00029
Iteration: 50, Log-Lik: -13120.373, Max-Change: 0.00072
Iteration: 51, Log-Lik: -13120.373, Max-Change: 0.00022
Iteration: 52, Log-Lik: -13120.373, Max-Change: 0.00099
Iteration: 53, Log-Lik: -13120.373, Max-Change: 0.00028
Iteration: 54, Log-Lik: -13120.373, Max-Change: 0.00069
Iteration: 55, Log-Lik: -13120.373, Max-Change: 0.00037
Iteration: 56, Log-Lik: -13120.373, Max-Change: 0.00096
Iteration: 57, Log-Lik: -13120.373, Max-Change: 0.00027
Iteration: 58, Log-Lik: -13120.373, Max-Change: 0.00024
Iteration: 59, Log-Lik: -13120.373, Max-Change: 0.00060
Iteration: 60, Log-Lik: -13120.373, Max-Change: 0.00091
Iteration: 61, Log-Lik: -13120.373, Max-Change: 0.00059
Iteration: 62, Log-Lik: -13120.373, Max-Change: 0.00088
Iteration: 63, Log-Lik: -13120.373, Max-Change: 0.00025
Iteration: 64, Log-Lik: -13120.373, Max-Change: 0.00022
Iteration: 65, Log-Lik: -13120.373, Max-Change: 0.00056
Iteration: 66, Log-Lik: -13120.372, Max-Change: 0.00084
Iteration: 67, Log-Lik: -13120.372, Max-Change: 0.00056
Iteration: 68, Log-Lik: -13120.372, Max-Change: 0.00082
Iteration: 69, Log-Lik: -13120.372, Max-Change: 0.00024
Iteration: 70, Log-Lik: -13120.372, Max-Change: 0.00021
Iteration: 71, Log-Lik: -13120.372, Max-Change: 0.00053
Iteration: 72, Log-Lik: -13120.372, Max-Change: 0.00079
Iteration: 73, Log-Lik: -13120.372, Max-Change: 0.00054
Iteration: 74, Log-Lik: -13120.372, Max-Change: 0.00079
Iteration: 75, Log-Lik: -13120.372, Max-Change: 0.00023
Iteration: 76, Log-Lik: -13120.372, Max-Change: 0.00020
Iteration: 77, Log-Lik: -13120.372, Max-Change: 0.00051
Iteration: 78, Log-Lik: -13120.372, Max-Change: 0.00075
Iteration: 79, Log-Lik: -13120.372, Max-Change: 0.00052
Iteration: 80, Log-Lik: -13120.372, Max-Change: 0.00077
Iteration: 81, Log-Lik: -13120.372, Max-Change: 0.00022
Iteration: 82, Log-Lik: -13120.372, Max-Change: 0.00020
Iteration: 83, Log-Lik: -13120.372, Max-Change: 0.00050
Iteration: 84, Log-Lik: -13120.372, Max-Change: 0.00073
Iteration: 85, Log-Lik: -13120.372, Max-Change: 0.00051
Iteration: 86, Log-Lik: -13120.372, Max-Change: 0.00075
Iteration: 87, Log-Lik: -13120.372, Max-Change: 0.00022
Iteration: 88, Log-Lik: -13120.372, Max-Change: 0.00019
Iteration: 89, Log-Lik: -13120.372, Max-Change: 0.00049
Iteration: 90, Log-Lik: -13120.372, Max-Change: 0.00072
Iteration: 91, Log-Lik: -13120.372, Max-Change: 0.00050
Iteration: 92, Log-Lik: -13120.372, Max-Change: 0.00074
Iteration: 93, Log-Lik: -13120.372, Max-Change: 0.00021
Iteration: 94, Log-Lik: -13120.372, Max-Change: 0.00019
Iteration: 95, Log-Lik: -13120.372, Max-Change: 0.00048
Iteration: 96, Log-Lik: -13120.372, Max-Change: 0.00070
Iteration: 97, Log-Lik: -13120.372, Max-Change: 0.00050
Iteration: 98, Log-Lik: -13120.372, Max-Change: 0.00072
Iteration: 99, Log-Lik: -13120.372, Max-Change: 0.00021
Iteration: 100, Log-Lik: -13120.372, Max-Change: 0.00019
Iteration: 101, Log-Lik: -13120.372, Max-Change: 0.00047
Iteration: 102, Log-Lik: -13120.372, Max-Change: 0.00069
Iteration: 103, Log-Lik: -13120.372, Max-Change: 0.00049
Iteration: 104, Log-Lik: -13120.372, Max-Change: 0.00071
Iteration: 105, Log-Lik: -13120.372, Max-Change: 0.00021
Iteration: 106, Log-Lik: -13120.372, Max-Change: 0.00018
Iteration: 107, Log-Lik: -13120.372, Max-Change: 0.00047
Iteration: 108, Log-Lik: -13120.372, Max-Change: 0.00068
Iteration: 109, Log-Lik: -13120.372, Max-Change: 0.00048
Iteration: 110, Log-Lik: -13120.372, Max-Change: 0.00070
Iteration: 111, Log-Lik: -13120.372, Max-Change: 0.00020
Iteration: 112, Log-Lik: -13120.372, Max-Change: 0.00018
Iteration: 113, Log-Lik: -13120.372, Max-Change: 0.00046
Iteration: 114, Log-Lik: -13120.372, Max-Change: 0.00067
Iteration: 115, Log-Lik: -13120.372, Max-Change: 0.00047
Iteration: 116, Log-Lik: -13120.372, Max-Change: 0.00069
Iteration: 117, Log-Lik: -13120.372, Max-Change: 0.00020
Iteration: 118, Log-Lik: -13120.372, Max-Change: 0.00018
Iteration: 119, Log-Lik: -13120.372, Max-Change: 0.00045
Iteration: 120, Log-Lik: -13120.372, Max-Change: 0.00066
Iteration: 121, Log-Lik: -13120.372, Max-Change: 0.00047
Iteration: 122, Log-Lik: -13120.372, Max-Change: 0.00068
Iteration: 123, Log-Lik: -13120.371, Max-Change: 0.00020
Iteration: 124, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 125, Log-Lik: -13120.371, Max-Change: 0.00045
Iteration: 126, Log-Lik: -13120.371, Max-Change: 0.00065
Iteration: 127, Log-Lik: -13120.371, Max-Change: 0.00046
Iteration: 128, Log-Lik: -13120.371, Max-Change: 0.00068
Iteration: 129, Log-Lik: -13120.371, Max-Change: 0.00020
Iteration: 130, Log-Lik: -13120.371, Max-Change: 0.00017
Iteration: 131, Log-Lik: -13120.371, Max-Change: 0.00044
Iteration: 132, Log-Lik: -13120.371, Max-Change: 0.00064
Iteration: 133, Log-Lik: -13120.371, Max-Change: 0.00046
Iteration: 134, Log-Lik: -13120.371, Max-Change: 0.00067
Iteration: 135, Log-Lik: -13120.371, Max-Change: 0.00019
Iteration: 136, Log-Lik: -13120.371, Max-Change: 0.00017
Iteration: 137, Log-Lik: -13120.371, Max-Change: 0.00044
Iteration: 138, Log-Lik: -13120.371, Max-Change: 0.00064
Iteration: 139, Log-Lik: -13120.371, Max-Change: 0.00045
Iteration: 140, Log-Lik: -13120.371, Max-Change: 0.00066
Iteration: 141, Log-Lik: -13120.371, Max-Change: 0.00019
Iteration: 142, Log-Lik: -13120.371, Max-Change: 0.00017
Iteration: 143, Log-Lik: -13120.371, Max-Change: 0.00043
Iteration: 144, Log-Lik: -13120.371, Max-Change: 0.00063
Iteration: 145, Log-Lik: -13120.371, Max-Change: 0.00045
Iteration: 146, Log-Lik: -13120.371, Max-Change: 0.00065
Iteration: 147, Log-Lik: -13120.371, Max-Change: 0.00019
Iteration: 148, Log-Lik: -13120.371, Max-Change: 0.00017
Iteration: 149, Log-Lik: -13120.371, Max-Change: 0.00043
Iteration: 150, Log-Lik: -13120.371, Max-Change: 0.00062
Iteration: 151, Log-Lik: -13120.371, Max-Change: 0.00044
Iteration: 152, Log-Lik: -13120.371, Max-Change: 0.00065
Iteration: 153, Log-Lik: -13120.371, Max-Change: 0.00019
Iteration: 154, Log-Lik: -13120.371, Max-Change: 0.00017
Iteration: 155, Log-Lik: -13120.371, Max-Change: 0.00042
Iteration: 156, Log-Lik: -13120.371, Max-Change: 0.00062
Iteration: 157, Log-Lik: -13120.371, Max-Change: 0.00044
Iteration: 158, Log-Lik: -13120.371, Max-Change: 0.00064
Iteration: 159, Log-Lik: -13120.371, Max-Change: 0.00019
Iteration: 160, Log-Lik: -13120.371, Max-Change: 0.00017
Iteration: 161, Log-Lik: -13120.371, Max-Change: 0.00042
Iteration: 162, Log-Lik: -13120.371, Max-Change: 0.00061
Iteration: 163, Log-Lik: -13120.371, Max-Change: 0.00044
Iteration: 164, Log-Lik: -13120.371, Max-Change: 0.00064
Iteration: 165, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 166, Log-Lik: -13120.371, Max-Change: 0.00016
Iteration: 167, Log-Lik: -13120.371, Max-Change: 0.00042
Iteration: 168, Log-Lik: -13120.371, Max-Change: 0.00061
Iteration: 169, Log-Lik: -13120.371, Max-Change: 0.00043
Iteration: 170, Log-Lik: -13120.371, Max-Change: 0.00063
Iteration: 171, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 172, Log-Lik: -13120.371, Max-Change: 0.00016
Iteration: 173, Log-Lik: -13120.371, Max-Change: 0.00041
Iteration: 174, Log-Lik: -13120.371, Max-Change: 0.00060
Iteration: 175, Log-Lik: -13120.371, Max-Change: 0.00043
Iteration: 176, Log-Lik: -13120.371, Max-Change: 0.00063
Iteration: 177, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 178, Log-Lik: -13120.371, Max-Change: 0.00016
Iteration: 179, Log-Lik: -13120.371, Max-Change: 0.00041
Iteration: 180, Log-Lik: -13120.371, Max-Change: 0.00060
Iteration: 181, Log-Lik: -13120.371, Max-Change: 0.00043
Iteration: 182, Log-Lik: -13120.371, Max-Change: 0.00062
Iteration: 183, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 184, Log-Lik: -13120.371, Max-Change: 0.00016
Iteration: 185, Log-Lik: -13120.371, Max-Change: 0.00041
Iteration: 186, Log-Lik: -13120.371, Max-Change: 0.00059
Iteration: 187, Log-Lik: -13120.371, Max-Change: 0.00042
Iteration: 188, Log-Lik: -13120.371, Max-Change: 0.00062
Iteration: 189, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 190, Log-Lik: -13120.371, Max-Change: 0.00016
Iteration: 191, Log-Lik: -13120.371, Max-Change: 0.00040
Iteration: 192, Log-Lik: -13120.371, Max-Change: 0.00059
Iteration: 193, Log-Lik: -13120.371, Max-Change: 0.00042
Iteration: 194, Log-Lik: -13120.371, Max-Change: 0.00061
Iteration: 195, Log-Lik: -13120.371, Max-Change: 0.00018
Iteration: 196, Log-Lik: -13120.371, Max-Change: 0.00016
Iteration: 197, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 198, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 199, Log-Lik: -13120.370, Max-Change: 0.00042
Iteration: 200, Log-Lik: -13120.370, Max-Change: 0.00061
Iteration: 201, Log-Lik: -13120.370, Max-Change: 0.00018
Iteration: 202, Log-Lik: -13120.370, Max-Change: 0.00016
Iteration: 203, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 204, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 205, Log-Lik: -13120.370, Max-Change: 0.00042
Iteration: 206, Log-Lik: -13120.370, Max-Change: 0.00060
Iteration: 207, Log-Lik: -13120.370, Max-Change: 0.00018
Iteration: 208, Log-Lik: -13120.370, Max-Change: 0.00016
Iteration: 209, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 210, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 211, Log-Lik: -13120.370, Max-Change: 0.00041
Iteration: 212, Log-Lik: -13120.370, Max-Change: 0.00060
Iteration: 213, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 214, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 215, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 216, Log-Lik: -13120.370, Max-Change: 0.00057
Iteration: 217, Log-Lik: -13120.370, Max-Change: 0.00041
Iteration: 218, Log-Lik: -13120.370, Max-Change: 0.00060
Iteration: 219, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 220, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 221, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 222, Log-Lik: -13120.370, Max-Change: 0.00057
Iteration: 223, Log-Lik: -13120.370, Max-Change: 0.00041
Iteration: 224, Log-Lik: -13120.370, Max-Change: 0.00060
Iteration: 225, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 226, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 227, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 228, Log-Lik: -13120.370, Max-Change: 0.00057
Iteration: 229, Log-Lik: -13120.370, Max-Change: 0.00041
Iteration: 230, Log-Lik: -13120.370, Max-Change: 0.00059
Iteration: 231, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 232, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 233, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 234, Log-Lik: -13120.370, Max-Change: 0.00057
Iteration: 235, Log-Lik: -13120.370, Max-Change: 0.00041
Iteration: 236, Log-Lik: -13120.370, Max-Change: 0.00059
Iteration: 237, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 238, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 239, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 240, Log-Lik: -13120.370, Max-Change: 0.00056
Iteration: 241, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 242, Log-Lik: -13120.370, Max-Change: 0.00059
Iteration: 243, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 244, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 245, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 246, Log-Lik: -13120.370, Max-Change: 0.00056
Iteration: 247, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 248, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 249, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 250, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 251, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 252, Log-Lik: -13120.370, Max-Change: 0.00056
Iteration: 253, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 254, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 255, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 256, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 257, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 258, Log-Lik: -13120.370, Max-Change: 0.00056
Iteration: 259, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 260, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 261, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 262, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 263, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 264, Log-Lik: -13120.370, Max-Change: 0.00055
Iteration: 265, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 266, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 267, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 268, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 269, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 270, Log-Lik: -13120.370, Max-Change: 0.00055
Iteration: 271, Log-Lik: -13120.370, Max-Change: 0.00040
Iteration: 272, Log-Lik: -13120.370, Max-Change: 0.00058
Iteration: 273, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 274, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 275, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 276, Log-Lik: -13120.370, Max-Change: 0.00055
Iteration: 277, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 278, Log-Lik: -13120.370, Max-Change: 0.00057
Iteration: 279, Log-Lik: -13120.370, Max-Change: 0.00017
Iteration: 280, Log-Lik: -13120.370, Max-Change: 0.00015
Iteration: 281, Log-Lik: -13120.370, Max-Change: 0.00038
Iteration: 282, Log-Lik: -13120.370, Max-Change: 0.00055
Iteration: 283, Log-Lik: -13120.370, Max-Change: 0.00039
Iteration: 284, Log-Lik: -13120.369, Max-Change: 0.00057
Iteration: 285, Log-Lik: -13120.369, Max-Change: 0.00017
Iteration: 286, Log-Lik: -13120.369, Max-Change: 0.00015
Iteration: 287, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 288, Log-Lik: -13120.369, Max-Change: 0.00055
Iteration: 289, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 290, Log-Lik: -13120.369, Max-Change: 0.00057
Iteration: 291, Log-Lik: -13120.369, Max-Change: 0.00017
Iteration: 292, Log-Lik: -13120.369, Max-Change: 0.00015
Iteration: 293, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 294, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 295, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 296, Log-Lik: -13120.369, Max-Change: 0.00057
Iteration: 297, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 298, Log-Lik: -13120.369, Max-Change: 0.00015
Iteration: 299, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 300, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 301, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 302, Log-Lik: -13120.369, Max-Change: 0.00057
Iteration: 303, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 304, Log-Lik: -13120.369, Max-Change: 0.00015
Iteration: 305, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 306, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 307, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 308, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 309, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 310, Log-Lik: -13120.369, Max-Change: 0.00015
Iteration: 311, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 312, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 313, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 314, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 315, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 316, Log-Lik: -13120.369, Max-Change: 0.00015
Iteration: 317, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 318, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 319, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 320, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 321, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 322, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 323, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 324, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 325, Log-Lik: -13120.369, Max-Change: 0.00039
Iteration: 326, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 327, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 328, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 329, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 330, Log-Lik: -13120.369, Max-Change: 0.00054
Iteration: 331, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 332, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 333, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 334, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 335, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 336, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 337, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 338, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 339, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 340, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 341, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 342, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 343, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 344, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 345, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 346, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 347, Log-Lik: -13120.369, Max-Change: 0.00037
Iteration: 348, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 349, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 350, Log-Lik: -13120.369, Max-Change: 0.00056
Iteration: 351, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 352, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 353, Log-Lik: -13120.369, Max-Change: 0.00036
Iteration: 354, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 355, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 356, Log-Lik: -13120.369, Max-Change: 0.00055
Iteration: 357, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 358, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 359, Log-Lik: -13120.369, Max-Change: 0.00036
Iteration: 360, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 361, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 362, Log-Lik: -13120.369, Max-Change: 0.00055
Iteration: 363, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 364, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 365, Log-Lik: -13120.369, Max-Change: 0.00036
Iteration: 366, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 367, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 368, Log-Lik: -13120.369, Max-Change: 0.00055
Iteration: 369, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 370, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 371, Log-Lik: -13120.369, Max-Change: 0.00036
Iteration: 372, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 373, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 374, Log-Lik: -13120.369, Max-Change: 0.00055
Iteration: 375, Log-Lik: -13120.369, Max-Change: 0.00016
Iteration: 376, Log-Lik: -13120.369, Max-Change: 0.00014
Iteration: 377, Log-Lik: -13120.369, Max-Change: 0.00036
Iteration: 378, Log-Lik: -13120.369, Max-Change: 0.00053
Iteration: 379, Log-Lik: -13120.369, Max-Change: 0.00038
Iteration: 380, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 381, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 382, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 383, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 384, Log-Lik: -13120.368, Max-Change: 0.00053
Iteration: 385, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 386, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 387, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 388, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 389, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 390, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 391, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 392, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 393, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 394, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 395, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 396, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 397, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 398, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 399, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 400, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 401, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 402, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 403, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 404, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 405, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 406, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 407, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 408, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 409, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 410, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 411, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 412, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 413, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 414, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 415, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 416, Log-Lik: -13120.368, Max-Change: 0.00055
Iteration: 417, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 418, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 419, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 420, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 421, Log-Lik: -13120.368, Max-Change: 0.00038
Iteration: 422, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 423, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 424, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 425, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 426, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 427, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 428, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 429, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 430, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 431, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 432, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 433, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 434, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 435, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 436, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 437, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 438, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 439, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 440, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 441, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 442, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 443, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 444, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 445, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 446, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 447, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 448, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 449, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 450, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 451, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 452, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 453, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 454, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 455, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 456, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 457, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 458, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 459, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 460, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 461, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 462, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 463, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 464, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 465, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 466, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 467, Log-Lik: -13120.368, Max-Change: 0.00036
Iteration: 468, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 469, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 470, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 471, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 472, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 473, Log-Lik: -13120.368, Max-Change: 0.00035
Iteration: 474, Log-Lik: -13120.368, Max-Change: 0.00052
Iteration: 475, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 476, Log-Lik: -13120.368, Max-Change: 0.00054
Iteration: 477, Log-Lik: -13120.368, Max-Change: 0.00016
Iteration: 478, Log-Lik: -13120.368, Max-Change: 0.00014
Iteration: 479, Log-Lik: -13120.368, Max-Change: 0.00035
Iteration: 480, Log-Lik: -13120.368, Max-Change: 0.00051
Iteration: 481, Log-Lik: -13120.368, Max-Change: 0.00037
Iteration: 482, Log-Lik: -13120.367, Max-Change: 0.00054
Iteration: 483, Log-Lik: -13120.367, Max-Change: 0.00016
Iteration: 484, Log-Lik: -13120.367, Max-Change: 0.00014
Iteration: 485, Log-Lik: -13120.367, Max-Change: 0.00035
Iteration: 486, Log-Lik: -13120.367, Max-Change: 0.00051
Iteration: 487, Log-Lik: -13120.367, Max-Change: 0.00037
Iteration: 488, Log-Lik: -13120.367, Max-Change: 0.00054
Iteration: 489, Log-Lik: -13120.367, Max-Change: 0.00016
Iteration: 490, Log-Lik: -13120.367, Max-Change: 0.00014
Iteration: 491, Log-Lik: -13120.367, Max-Change: 0.00035
Iteration: 492, Log-Lik: -13120.367, Max-Change: 0.00051
Iteration: 493, Log-Lik: -13120.367, Max-Change: 0.00037
Iteration: 494, Log-Lik: -13120.367, Max-Change: 0.00054
Iteration: 495, Log-Lik: -13120.367, Max-Change: 0.00016
Iteration: 496, Log-Lik: -13120.367, Max-Change: 0.00014
Iteration: 497, Log-Lik: -13120.367, Max-Change: 0.00035
Iteration: 498, Log-Lik: -13120.367, Max-Change: 0.00051
Iteration: 499, Log-Lik: -13120.367, Max-Change: 0.00037
Iteration: 500, Log-Lik: -13120.367, Max-Change: 0.00054</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>EM cycles terminated after 500 iterations.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>

Calculating information matrix...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>threepl_params <span class="ot">&lt;-</span> <span class="fu">coef</span>(threepl_fit, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>threepl_items <span class="ot">&lt;-</span> threepl_params<span class="sc">$</span>items</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(threepl_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 a          b            g u
reason.4  1.965832 -0.2869613 0.1220243277 1
reason.16 1.419231 -0.7995733 0.0022155571 1
reason.17 1.780427 -0.7076754 0.0020240288 1
reason.19 1.379131 -0.4514928 0.0005308146 1
letter.7  1.535846 -0.3622950 0.0007297169 1
letter.33 1.336533 -0.2751526 0.0010139285 1</code></pre>
</div>
</div>
<p>결과의 처음 두 열은 SAPA 데이터 세트의 각 문항에 대한 문항 변별도 및 난이도 모수를 보여줍니다. 1PL 및 2PL 모델과 달리 3PL 모델의 세 번째 열(즉, g)은 0이 아닙니다. 이 열은 낮은 점근 모수를 보여줍니다. item 1(reason.4)은 일반적으로 추측도가 최소화되는 다른 출력된 문항에 비해 추측도 모수가 큽니다.</p>
<p>추측도가 문항에 미치는 영향을 확인하기 위해 item 1(reason.4)과 4(reason.19)에 대한 ICC 그래프를 그립니다. 그림 5.12는 잠재 특성이 작아질수록(예: <span class="math inline">\(\theta &lt; -2\)</span>) 문항 1의 정답 확률이 0.12에 가까워지는 반면, item 4의 확률은 거의 0에 가까워지는 것을 보여줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(threepl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>), </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">facet_items =</span> <span class="cn">FALSE</span>, <span class="at">auto.key =</span> <span class="fu">list</span>(<span class="at">points =</span> <span class="cn">FALSE</span>,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">lines =</span> <span class="cn">TRUE</span>, <span class="at">columns =</span> <span class="dv">2</span>),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">par.settings =</span> <span class="fu">simpleTheme</span>(<span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="모수-로지스틱-모델-3" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="모수-로지스틱-모델-3"><span class="header-section-number">5.3.4</span> 4모수 로지스틱 모델</h3>
<p>Barton과 Lord(1981)가 도입한 4모수 로지스틱(4PL) 모델은 3PL 모델의 특수한 경우입니다. 4PL 모델에서는 문항이 하한 및 상한 점근 모수를 모두 가질 수 있습니다. 상한 점근 모수는 피험자의 잠재 특성 수준에 관계없이 정답을 맞힐 확률이 1(즉, 100%)에 가까워지는 것을 방지하는 상한 모수로 설명할 수 있습니다. 4PL은 다음과 같이 작성됩니다.</p>
<p><span class="math display">\[
P(Y_{ij}=1|\theta_j, a_i, b_i, c_i, u_i) = c_i + {u_i-c_i \over 1+exp(-Da_i(\theta_j-b_i))}
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(u_i\)</span> 모수는 상부 점근을 나타냅니다.</li>
</ul>
<p>이 추가 모수는 <span class="math inline">\(c_i\)</span> 모수가 0이 아니고 <span class="math inline">\(u_i\)</span> 모수가 1이 아닐 때 방정식의 분자를 1보다 작게 만듭니다(4PL 모델에 대한 자세한 설명은 Magis(2013) 참조).</p>
<p>성취도 및 적성과 같은 잠재 특성을 모델링하는 데는 3PL 모델이 더 일반적이지만, 신경증, 개방성, 공격성 및 동기 부여와 같은 비인지적 성격 특성에는 이러한 특성의 최고 수준에 도달할 확률이 1에 가까워지지 않을 수 있으므로 4PL 모델이 더 적합할 수 있습니다. IRT 모델에 상위 점근 모수를 포함할 경우의 이점은 여러 연구에서 입증되었습니다(Loken &amp; Rulison, 2010; Osgood, McMorris, &amp; Potenza, 2002; Reise &amp; Waller, 2009; Tavares, Andrade, &amp; Pereira, 2004).</p>
<p>다음 예에서는 SAPA 데이터 세트에 대한 4PL 모델을 추정합니다. itemtype = “4PL”을 설정하여 4PL 모델을 추정합니다. 이전과 마찬가지로, 적합 모델을 fourpl_fit으로 저장한 다음 추정된 문항 모수를 추출하고 문항 모수의 처음 몇 행을 출력합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>fourpl_mod <span class="ot">&lt;-</span> <span class="st">"F = 1 - 16"</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>fourpl_fit <span class="ot">&lt;-</span> <span class="fu">mirt</span>(<span class="at">data =</span> SAPA, <span class="at">model =</span> fourpl_mod,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">itemtype =</span> <span class="st">"4PL"</span>, <span class="at">SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Iteration: 1, Log-Lik: -14241.720, Max-Change: 2.22037
Iteration: 2, Log-Lik: -13336.802, Max-Change: 0.95506
Iteration: 3, Log-Lik: -13171.878, Max-Change: 0.91670
Iteration: 4, Log-Lik: -13121.825, Max-Change: 0.75554
Iteration: 5, Log-Lik: -13099.489, Max-Change: 0.59099
Iteration: 6, Log-Lik: -13088.709, Max-Change: 0.51223
Iteration: 7, Log-Lik: -13082.537, Max-Change: 0.50146
Iteration: 8, Log-Lik: -13078.456, Max-Change: 0.45543
Iteration: 9, Log-Lik: -13075.870, Max-Change: 0.49227
Iteration: 10, Log-Lik: -13074.620, Max-Change: 0.27210
Iteration: 11, Log-Lik: -13069.813, Max-Change: 0.42392
Iteration: 12, Log-Lik: -13069.109, Max-Change: 0.67288
Iteration: 13, Log-Lik: -13068.027, Max-Change: 0.10701
Iteration: 14, Log-Lik: -13067.772, Max-Change: 0.83409
Iteration: 15, Log-Lik: -13067.484, Max-Change: 0.43269
Iteration: 16, Log-Lik: -13067.314, Max-Change: 0.49296
Iteration: 17, Log-Lik: -13067.157, Max-Change: 0.67363
Iteration: 18, Log-Lik: -13066.999, Max-Change: 0.64192
Iteration: 19, Log-Lik: -13066.536, Max-Change: 0.12335
Iteration: 20, Log-Lik: -13066.375, Max-Change: 0.11240
Iteration: 21, Log-Lik: -13066.331, Max-Change: 0.06089
Iteration: 22, Log-Lik: -13066.302, Max-Change: 0.01846
Iteration: 23, Log-Lik: -13066.286, Max-Change: 0.01666
Iteration: 24, Log-Lik: -13066.274, Max-Change: 0.01310
Iteration: 25, Log-Lik: -13066.250, Max-Change: 0.01981
Iteration: 26, Log-Lik: -13066.239, Max-Change: 0.29737
Iteration: 27, Log-Lik: -13066.197, Max-Change: 0.00984
Iteration: 28, Log-Lik: -13066.197, Max-Change: 0.00985
Iteration: 29, Log-Lik: -13066.192, Max-Change: 0.00923
Iteration: 30, Log-Lik: -13066.188, Max-Change: 0.28666
Iteration: 31, Log-Lik: -13066.149, Max-Change: 0.00845
Iteration: 32, Log-Lik: -13066.145, Max-Change: 0.00813
Iteration: 33, Log-Lik: -13066.141, Max-Change: 0.56865
Iteration: 34, Log-Lik: -13066.089, Max-Change: 0.00684
Iteration: 35, Log-Lik: -13066.085, Max-Change: 0.00658
Iteration: 36, Log-Lik: -13066.083, Max-Change: 0.00497
Iteration: 37, Log-Lik: -13066.080, Max-Change: 0.00577
Iteration: 38, Log-Lik: -13066.077, Max-Change: 0.00483
Iteration: 39, Log-Lik: -13066.076, Max-Change: 0.00481
Iteration: 40, Log-Lik: -13066.071, Max-Change: 0.00219
Iteration: 41, Log-Lik: -13066.070, Max-Change: 0.00172
Iteration: 42, Log-Lik: -13066.070, Max-Change: 0.00041
Iteration: 43, Log-Lik: -13066.069, Max-Change: 0.00189
Iteration: 44, Log-Lik: -13066.069, Max-Change: 0.00047
Iteration: 45, Log-Lik: -13066.069, Max-Change: 0.00131
Iteration: 46, Log-Lik: -13066.069, Max-Change: 0.01761
Iteration: 47, Log-Lik: -13066.067, Max-Change: 0.00170
Iteration: 48, Log-Lik: -13066.066, Max-Change: 0.00090
Iteration: 49, Log-Lik: -13066.066, Max-Change: 0.00239
Iteration: 50, Log-Lik: -13066.066, Max-Change: 0.00150
Iteration: 51, Log-Lik: -13066.066, Max-Change: 0.00129
Iteration: 52, Log-Lik: -13066.066, Max-Change: 0.00206
Iteration: 53, Log-Lik: -13066.066, Max-Change: 0.00172
Iteration: 54, Log-Lik: -13066.066, Max-Change: 0.00042
Iteration: 55, Log-Lik: -13066.066, Max-Change: 0.00038
Iteration: 56, Log-Lik: -13066.066, Max-Change: 0.00107
Iteration: 57, Log-Lik: -13066.065, Max-Change: 0.00127
Iteration: 58, Log-Lik: -13066.065, Max-Change: 0.00042
Iteration: 59, Log-Lik: -13066.065, Max-Change: 0.00049
Iteration: 60, Log-Lik: -13066.065, Max-Change: 0.00062
Iteration: 61, Log-Lik: -13066.065, Max-Change: 0.00040
Iteration: 62, Log-Lik: -13066.065, Max-Change: 0.00050
Iteration: 63, Log-Lik: -13066.065, Max-Change: 0.00059
Iteration: 64, Log-Lik: -13066.065, Max-Change: 0.00041
Iteration: 65, Log-Lik: -13066.065, Max-Change: 0.00048
Iteration: 66, Log-Lik: -13066.065, Max-Change: 0.00060
Iteration: 67, Log-Lik: -13066.065, Max-Change: 0.00040
Iteration: 68, Log-Lik: -13066.065, Max-Change: 0.00050
Iteration: 69, Log-Lik: -13066.065, Max-Change: 0.00058
Iteration: 70, Log-Lik: -13066.065, Max-Change: 0.00041
Iteration: 71, Log-Lik: -13066.065, Max-Change: 0.00048
Iteration: 72, Log-Lik: -13066.065, Max-Change: 0.00059
Iteration: 73, Log-Lik: -13066.065, Max-Change: 0.00039
Iteration: 74, Log-Lik: -13066.065, Max-Change: 0.00049
Iteration: 75, Log-Lik: -13066.065, Max-Change: 0.00058
Iteration: 76, Log-Lik: -13066.065, Max-Change: 0.00040
Iteration: 77, Log-Lik: -13066.064, Max-Change: 0.00047
Iteration: 78, Log-Lik: -13066.064, Max-Change: 0.00059
Iteration: 79, Log-Lik: -13066.064, Max-Change: 0.00039
Iteration: 80, Log-Lik: -13066.064, Max-Change: 0.00048
Iteration: 81, Log-Lik: -13066.064, Max-Change: 0.00057
Iteration: 82, Log-Lik: -13066.064, Max-Change: 0.00040
Iteration: 83, Log-Lik: -13066.064, Max-Change: 0.00047
Iteration: 84, Log-Lik: -13066.064, Max-Change: 0.00058
Iteration: 85, Log-Lik: -13066.064, Max-Change: 0.00038
Iteration: 86, Log-Lik: -13066.064, Max-Change: 0.00048
Iteration: 87, Log-Lik: -13066.064, Max-Change: 0.00056
Iteration: 88, Log-Lik: -13066.064, Max-Change: 0.00039
Iteration: 89, Log-Lik: -13066.064, Max-Change: 0.00046
Iteration: 90, Log-Lik: -13066.064, Max-Change: 0.00057
Iteration: 91, Log-Lik: -13066.064, Max-Change: 0.00038
Iteration: 92, Log-Lik: -13066.064, Max-Change: 0.00047
Iteration: 93, Log-Lik: -13066.064, Max-Change: 0.00056
Iteration: 94, Log-Lik: -13066.064, Max-Change: 0.00039
Iteration: 95, Log-Lik: -13066.064, Max-Change: 0.00046
Iteration: 96, Log-Lik: -13066.064, Max-Change: 0.00057
Iteration: 97, Log-Lik: -13066.064, Max-Change: 0.00037
Iteration: 98, Log-Lik: -13066.064, Max-Change: 0.00047
Iteration: 99, Log-Lik: -13066.064, Max-Change: 0.00055
Iteration: 100, Log-Lik: -13066.063, Max-Change: 0.00039
Iteration: 101, Log-Lik: -13066.063, Max-Change: 0.00045
Iteration: 102, Log-Lik: -13066.063, Max-Change: 0.00056
Iteration: 103, Log-Lik: -13066.063, Max-Change: 0.00037
Iteration: 104, Log-Lik: -13066.063, Max-Change: 0.00046
Iteration: 105, Log-Lik: -13066.063, Max-Change: 0.00055
Iteration: 106, Log-Lik: -13066.063, Max-Change: 0.00038
Iteration: 107, Log-Lik: -13066.063, Max-Change: 0.00045
Iteration: 108, Log-Lik: -13066.063, Max-Change: 0.00056
Iteration: 109, Log-Lik: -13066.063, Max-Change: 0.00037
Iteration: 110, Log-Lik: -13066.063, Max-Change: 0.00046
Iteration: 111, Log-Lik: -13066.063, Max-Change: 0.00054
Iteration: 112, Log-Lik: -13066.063, Max-Change: 0.00038
Iteration: 113, Log-Lik: -13066.063, Max-Change: 0.00045
Iteration: 114, Log-Lik: -13066.063, Max-Change: 0.00055
Iteration: 115, Log-Lik: -13066.063, Max-Change: 0.00037
Iteration: 116, Log-Lik: -13066.063, Max-Change: 0.00046
Iteration: 117, Log-Lik: -13066.063, Max-Change: 0.00054
Iteration: 118, Log-Lik: -13066.063, Max-Change: 0.00038
Iteration: 119, Log-Lik: -13066.063, Max-Change: 0.00044
Iteration: 120, Log-Lik: -13066.063, Max-Change: 0.00055
Iteration: 121, Log-Lik: -13066.063, Max-Change: 0.00036
Iteration: 122, Log-Lik: -13066.063, Max-Change: 0.00045
Iteration: 123, Log-Lik: -13066.063, Max-Change: 0.00053
Iteration: 124, Log-Lik: -13066.062, Max-Change: 0.00037
Iteration: 125, Log-Lik: -13066.062, Max-Change: 0.00044
Iteration: 126, Log-Lik: -13066.062, Max-Change: 0.00054
Iteration: 127, Log-Lik: -13066.062, Max-Change: 0.00036
Iteration: 128, Log-Lik: -13066.062, Max-Change: 0.00045
Iteration: 129, Log-Lik: -13066.062, Max-Change: 0.00053
Iteration: 130, Log-Lik: -13066.062, Max-Change: 0.00037
Iteration: 131, Log-Lik: -13066.062, Max-Change: 0.00044
Iteration: 132, Log-Lik: -13066.062, Max-Change: 0.00054
Iteration: 133, Log-Lik: -13066.062, Max-Change: 0.00036
Iteration: 134, Log-Lik: -13066.062, Max-Change: 0.00045
Iteration: 135, Log-Lik: -13066.062, Max-Change: 0.00053
Iteration: 136, Log-Lik: -13066.062, Max-Change: 0.00037
Iteration: 137, Log-Lik: -13066.062, Max-Change: 0.00044
Iteration: 138, Log-Lik: -13066.062, Max-Change: 0.00054
Iteration: 139, Log-Lik: -13066.062, Max-Change: 0.00036
Iteration: 140, Log-Lik: -13066.062, Max-Change: 0.00044
Iteration: 141, Log-Lik: -13066.062, Max-Change: 0.00053
Iteration: 142, Log-Lik: -13066.062, Max-Change: 0.00037
Iteration: 143, Log-Lik: -13066.062, Max-Change: 0.00043
Iteration: 144, Log-Lik: -13066.062, Max-Change: 0.00054
Iteration: 145, Log-Lik: -13066.062, Max-Change: 0.00036
Iteration: 146, Log-Lik: -13066.062, Max-Change: 0.00044
Iteration: 147, Log-Lik: -13066.062, Max-Change: 0.00052
Iteration: 148, Log-Lik: -13066.062, Max-Change: 0.00037
Iteration: 149, Log-Lik: -13066.062, Max-Change: 0.00043
Iteration: 150, Log-Lik: -13066.061, Max-Change: 0.00053
Iteration: 151, Log-Lik: -13066.061, Max-Change: 0.00035
Iteration: 152, Log-Lik: -13066.061, Max-Change: 0.00044
Iteration: 153, Log-Lik: -13066.061, Max-Change: 0.00052
Iteration: 154, Log-Lik: -13066.061, Max-Change: 0.00036
Iteration: 155, Log-Lik: -13066.061, Max-Change: 0.00043
Iteration: 156, Log-Lik: -13066.061, Max-Change: 0.00053
Iteration: 157, Log-Lik: -13066.061, Max-Change: 0.00035
Iteration: 158, Log-Lik: -13066.061, Max-Change: 0.00044
Iteration: 159, Log-Lik: -13066.061, Max-Change: 0.00052
Iteration: 160, Log-Lik: -13066.061, Max-Change: 0.00036
Iteration: 161, Log-Lik: -13066.061, Max-Change: 0.00043
Iteration: 162, Log-Lik: -13066.061, Max-Change: 0.00053
Iteration: 163, Log-Lik: -13066.061, Max-Change: 0.00035
Iteration: 164, Log-Lik: -13066.061, Max-Change: 0.00044
Iteration: 165, Log-Lik: -13066.061, Max-Change: 0.00052
Iteration: 166, Log-Lik: -13066.061, Max-Change: 0.00036
Iteration: 167, Log-Lik: -13066.061, Max-Change: 0.00043
Iteration: 168, Log-Lik: -13066.061, Max-Change: 0.00053
Iteration: 169, Log-Lik: -13066.061, Max-Change: 0.00035
Iteration: 170, Log-Lik: -13066.061, Max-Change: 0.00043
Iteration: 171, Log-Lik: -13066.061, Max-Change: 0.00052
Iteration: 172, Log-Lik: -13066.061, Max-Change: 0.00036
Iteration: 173, Log-Lik: -13066.061, Max-Change: 0.00042
Iteration: 174, Log-Lik: -13066.061, Max-Change: 0.00052
Iteration: 175, Log-Lik: -13066.061, Max-Change: 0.00035
Iteration: 176, Log-Lik: -13066.061, Max-Change: 0.00043
Iteration: 177, Log-Lik: -13066.060, Max-Change: 0.00051
Iteration: 178, Log-Lik: -13066.060, Max-Change: 0.00036
Iteration: 179, Log-Lik: -13066.060, Max-Change: 0.00042
Iteration: 180, Log-Lik: -13066.060, Max-Change: 0.00052
Iteration: 181, Log-Lik: -13066.060, Max-Change: 0.00035
Iteration: 182, Log-Lik: -13066.060, Max-Change: 0.00043
Iteration: 183, Log-Lik: -13066.060, Max-Change: 0.00051
Iteration: 184, Log-Lik: -13066.060, Max-Change: 0.00036
Iteration: 185, Log-Lik: -13066.060, Max-Change: 0.00042
Iteration: 186, Log-Lik: -13066.060, Max-Change: 0.00052
Iteration: 187, Log-Lik: -13066.060, Max-Change: 0.00035
Iteration: 188, Log-Lik: -13066.060, Max-Change: 0.00043
Iteration: 189, Log-Lik: -13066.060, Max-Change: 0.00051
Iteration: 190, Log-Lik: -13066.060, Max-Change: 0.00036
Iteration: 191, Log-Lik: -13066.060, Max-Change: 0.00042
Iteration: 192, Log-Lik: -13066.060, Max-Change: 0.00052
Iteration: 193, Log-Lik: -13066.060, Max-Change: 0.00035
Iteration: 194, Log-Lik: -13066.060, Max-Change: 0.00043
Iteration: 195, Log-Lik: -13066.060, Max-Change: 0.00051
Iteration: 196, Log-Lik: -13066.060, Max-Change: 0.00036
Iteration: 197, Log-Lik: -13066.060, Max-Change: 0.00042
Iteration: 198, Log-Lik: -13066.060, Max-Change: 0.00052
Iteration: 199, Log-Lik: -13066.060, Max-Change: 0.00035
Iteration: 200, Log-Lik: -13066.060, Max-Change: 0.00043
Iteration: 201, Log-Lik: -13066.060, Max-Change: 0.00051
Iteration: 202, Log-Lik: -13066.060, Max-Change: 0.00035
Iteration: 203, Log-Lik: -13066.060, Max-Change: 0.00042
Iteration: 204, Log-Lik: -13066.059, Max-Change: 0.00052
Iteration: 205, Log-Lik: -13066.059, Max-Change: 0.00035
Iteration: 206, Log-Lik: -13066.059, Max-Change: 0.00043
Iteration: 207, Log-Lik: -13066.059, Max-Change: 0.00051
Iteration: 208, Log-Lik: -13066.059, Max-Change: 0.00035
Iteration: 209, Log-Lik: -13066.059, Max-Change: 0.00042
Iteration: 210, Log-Lik: -13066.059, Max-Change: 0.00052
Iteration: 211, Log-Lik: -13066.059, Max-Change: 0.00034
Iteration: 212, Log-Lik: -13066.059, Max-Change: 0.00043
Iteration: 213, Log-Lik: -13066.059, Max-Change: 0.00051
Iteration: 214, Log-Lik: -13066.059, Max-Change: 0.00035
Iteration: 215, Log-Lik: -13066.059, Max-Change: 0.00042
Iteration: 216, Log-Lik: -13066.059, Max-Change: 0.00051
Iteration: 217, Log-Lik: -13066.059, Max-Change: 0.00034
Iteration: 218, Log-Lik: -13066.059, Max-Change: 0.00043
Iteration: 219, Log-Lik: -13066.059, Max-Change: 0.00051
Iteration: 220, Log-Lik: -13066.059, Max-Change: 0.00035
Iteration: 221, Log-Lik: -13066.059, Max-Change: 0.00042
Iteration: 222, Log-Lik: -13066.059, Max-Change: 0.00051
Iteration: 223, Log-Lik: -13066.059, Max-Change: 0.00034
Iteration: 224, Log-Lik: -13066.059, Max-Change: 0.00042
Iteration: 225, Log-Lik: -13066.059, Max-Change: 0.00050
Iteration: 226, Log-Lik: -13066.059, Max-Change: 0.00035
Iteration: 227, Log-Lik: -13066.059, Max-Change: 0.00042
Iteration: 228, Log-Lik: -13066.059, Max-Change: 0.00051
Iteration: 229, Log-Lik: -13066.059, Max-Change: 0.00034
Iteration: 230, Log-Lik: -13066.059, Max-Change: 0.00042
Iteration: 231, Log-Lik: -13066.059, Max-Change: 0.00050
Iteration: 232, Log-Lik: -13066.058, Max-Change: 0.00035
Iteration: 233, Log-Lik: -13066.058, Max-Change: 0.00042
Iteration: 234, Log-Lik: -13066.058, Max-Change: 0.00051
Iteration: 235, Log-Lik: -13066.058, Max-Change: 0.00034
Iteration: 236, Log-Lik: -13066.058, Max-Change: 0.00042
Iteration: 237, Log-Lik: -13066.058, Max-Change: 0.00050
Iteration: 238, Log-Lik: -13066.058, Max-Change: 0.00035
Iteration: 239, Log-Lik: -13066.058, Max-Change: 0.00041
Iteration: 240, Log-Lik: -13066.058, Max-Change: 0.00051
Iteration: 241, Log-Lik: -13066.058, Max-Change: 0.00034
Iteration: 242, Log-Lik: -13066.058, Max-Change: 0.00042
Iteration: 243, Log-Lik: -13066.058, Max-Change: 0.00050
Iteration: 244, Log-Lik: -13066.058, Max-Change: 0.00035
Iteration: 245, Log-Lik: -13066.058, Max-Change: 0.00041
Iteration: 246, Log-Lik: -13066.058, Max-Change: 0.00051
Iteration: 247, Log-Lik: -13066.058, Max-Change: 0.00034
Iteration: 248, Log-Lik: -13066.058, Max-Change: 0.00042
Iteration: 249, Log-Lik: -13066.058, Max-Change: 0.00050
Iteration: 250, Log-Lik: -13066.058, Max-Change: 0.00035
Iteration: 251, Log-Lik: -13066.058, Max-Change: 0.00041
Iteration: 252, Log-Lik: -13066.058, Max-Change: 0.00051
Iteration: 253, Log-Lik: -13066.058, Max-Change: 0.00034
Iteration: 254, Log-Lik: -13066.058, Max-Change: 0.00042
Iteration: 255, Log-Lik: -13066.058, Max-Change: 0.00050
Iteration: 256, Log-Lik: -13066.058, Max-Change: 0.00035
Iteration: 257, Log-Lik: -13066.058, Max-Change: 0.00041
Iteration: 258, Log-Lik: -13066.058, Max-Change: 0.00051
Iteration: 259, Log-Lik: -13066.058, Max-Change: 0.00034
Iteration: 260, Log-Lik: -13066.057, Max-Change: 0.00042
Iteration: 261, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 262, Log-Lik: -13066.057, Max-Change: 0.00035
Iteration: 263, Log-Lik: -13066.057, Max-Change: 0.00041
Iteration: 264, Log-Lik: -13066.057, Max-Change: 0.00051
Iteration: 265, Log-Lik: -13066.057, Max-Change: 0.00034
Iteration: 266, Log-Lik: -13066.057, Max-Change: 0.00042
Iteration: 267, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 268, Log-Lik: -13066.057, Max-Change: 0.00035
Iteration: 269, Log-Lik: -13066.057, Max-Change: 0.00041
Iteration: 270, Log-Lik: -13066.057, Max-Change: 0.00051
Iteration: 271, Log-Lik: -13066.057, Max-Change: 0.00034
Iteration: 272, Log-Lik: -13066.057, Max-Change: 0.00042
Iteration: 273, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 274, Log-Lik: -13066.057, Max-Change: 0.00035
Iteration: 275, Log-Lik: -13066.057, Max-Change: 0.00041
Iteration: 276, Log-Lik: -13066.057, Max-Change: 0.00051
Iteration: 277, Log-Lik: -13066.057, Max-Change: 0.00034
Iteration: 278, Log-Lik: -13066.057, Max-Change: 0.00042
Iteration: 279, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 280, Log-Lik: -13066.057, Max-Change: 0.00035
Iteration: 281, Log-Lik: -13066.057, Max-Change: 0.00041
Iteration: 282, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 283, Log-Lik: -13066.057, Max-Change: 0.00034
Iteration: 284, Log-Lik: -13066.057, Max-Change: 0.00042
Iteration: 285, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 286, Log-Lik: -13066.057, Max-Change: 0.00035
Iteration: 287, Log-Lik: -13066.057, Max-Change: 0.00041
Iteration: 288, Log-Lik: -13066.057, Max-Change: 0.00050
Iteration: 289, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 290, Log-Lik: -13066.056, Max-Change: 0.00042
Iteration: 291, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 292, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 293, Log-Lik: -13066.056, Max-Change: 0.00041
Iteration: 294, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 295, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 296, Log-Lik: -13066.056, Max-Change: 0.00042
Iteration: 297, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 298, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 299, Log-Lik: -13066.056, Max-Change: 0.00041
Iteration: 300, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 301, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 302, Log-Lik: -13066.056, Max-Change: 0.00042
Iteration: 303, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 304, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 305, Log-Lik: -13066.056, Max-Change: 0.00041
Iteration: 306, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 307, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 308, Log-Lik: -13066.056, Max-Change: 0.00042
Iteration: 309, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 310, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 311, Log-Lik: -13066.056, Max-Change: 0.00041
Iteration: 312, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 313, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 314, Log-Lik: -13066.056, Max-Change: 0.00041
Iteration: 315, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 316, Log-Lik: -13066.056, Max-Change: 0.00034
Iteration: 317, Log-Lik: -13066.056, Max-Change: 0.00041
Iteration: 318, Log-Lik: -13066.056, Max-Change: 0.00050
Iteration: 319, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 320, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 321, Log-Lik: -13066.055, Max-Change: 0.00049
Iteration: 322, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 323, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 324, Log-Lik: -13066.055, Max-Change: 0.00050
Iteration: 325, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 326, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 327, Log-Lik: -13066.055, Max-Change: 0.00049
Iteration: 328, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 329, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 330, Log-Lik: -13066.055, Max-Change: 0.00050
Iteration: 331, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 332, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 333, Log-Lik: -13066.055, Max-Change: 0.00049
Iteration: 334, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 335, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 336, Log-Lik: -13066.055, Max-Change: 0.00050
Iteration: 337, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 338, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 339, Log-Lik: -13066.055, Max-Change: 0.00049
Iteration: 340, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 341, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 342, Log-Lik: -13066.055, Max-Change: 0.00050
Iteration: 343, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 344, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 345, Log-Lik: -13066.055, Max-Change: 0.00049
Iteration: 346, Log-Lik: -13066.055, Max-Change: 0.00034
Iteration: 347, Log-Lik: -13066.055, Max-Change: 0.00041
Iteration: 348, Log-Lik: -13066.054, Max-Change: 0.00050
Iteration: 349, Log-Lik: -13066.054, Max-Change: 0.00034
Iteration: 350, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 351, Log-Lik: -13066.054, Max-Change: 0.00049
Iteration: 352, Log-Lik: -13066.054, Max-Change: 0.00034
Iteration: 353, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 354, Log-Lik: -13066.054, Max-Change: 0.00050
Iteration: 355, Log-Lik: -13066.054, Max-Change: 0.00033
Iteration: 356, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 357, Log-Lik: -13066.054, Max-Change: 0.00049
Iteration: 358, Log-Lik: -13066.054, Max-Change: 0.00034
Iteration: 359, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 360, Log-Lik: -13066.054, Max-Change: 0.00050
Iteration: 361, Log-Lik: -13066.054, Max-Change: 0.00033
Iteration: 362, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 363, Log-Lik: -13066.054, Max-Change: 0.00049
Iteration: 364, Log-Lik: -13066.054, Max-Change: 0.00034
Iteration: 365, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 366, Log-Lik: -13066.054, Max-Change: 0.00050
Iteration: 367, Log-Lik: -13066.054, Max-Change: 0.00033
Iteration: 368, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 369, Log-Lik: -13066.054, Max-Change: 0.00049
Iteration: 370, Log-Lik: -13066.054, Max-Change: 0.00034
Iteration: 371, Log-Lik: -13066.054, Max-Change: 0.00040
Iteration: 372, Log-Lik: -13066.054, Max-Change: 0.00050
Iteration: 373, Log-Lik: -13066.054, Max-Change: 0.00033
Iteration: 374, Log-Lik: -13066.054, Max-Change: 0.00041
Iteration: 375, Log-Lik: -13066.054, Max-Change: 0.00049
Iteration: 376, Log-Lik: -13066.054, Max-Change: 0.00034
Iteration: 377, Log-Lik: -13066.054, Max-Change: 0.00040
Iteration: 378, Log-Lik: -13066.053, Max-Change: 0.00050
Iteration: 379, Log-Lik: -13066.053, Max-Change: 0.00033
Iteration: 380, Log-Lik: -13066.053, Max-Change: 0.00041
Iteration: 381, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 382, Log-Lik: -13066.053, Max-Change: 0.00034
Iteration: 383, Log-Lik: -13066.053, Max-Change: 0.00040
Iteration: 384, Log-Lik: -13066.053, Max-Change: 0.00050
Iteration: 385, Log-Lik: -13066.053, Max-Change: 0.00033
Iteration: 386, Log-Lik: -13066.053, Max-Change: 0.00041
Iteration: 387, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 388, Log-Lik: -13066.053, Max-Change: 0.00034
Iteration: 389, Log-Lik: -13066.053, Max-Change: 0.00040
Iteration: 390, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 391, Log-Lik: -13066.053, Max-Change: 0.00033
Iteration: 392, Log-Lik: -13066.053, Max-Change: 0.00041
Iteration: 393, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 394, Log-Lik: -13066.053, Max-Change: 0.00034
Iteration: 395, Log-Lik: -13066.053, Max-Change: 0.00040
Iteration: 396, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 397, Log-Lik: -13066.053, Max-Change: 0.00033
Iteration: 398, Log-Lik: -13066.053, Max-Change: 0.00041
Iteration: 399, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 400, Log-Lik: -13066.053, Max-Change: 0.00034
Iteration: 401, Log-Lik: -13066.053, Max-Change: 0.00040
Iteration: 402, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 403, Log-Lik: -13066.053, Max-Change: 0.00033
Iteration: 404, Log-Lik: -13066.053, Max-Change: 0.00041
Iteration: 405, Log-Lik: -13066.053, Max-Change: 0.00049
Iteration: 406, Log-Lik: -13066.053, Max-Change: 0.00034
Iteration: 407, Log-Lik: -13066.053, Max-Change: 0.00040
Iteration: 408, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 409, Log-Lik: -13066.052, Max-Change: 0.00033
Iteration: 410, Log-Lik: -13066.052, Max-Change: 0.00041
Iteration: 411, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 412, Log-Lik: -13066.052, Max-Change: 0.00034
Iteration: 413, Log-Lik: -13066.052, Max-Change: 0.00040
Iteration: 414, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 415, Log-Lik: -13066.052, Max-Change: 0.00033
Iteration: 416, Log-Lik: -13066.052, Max-Change: 0.00041
Iteration: 417, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 418, Log-Lik: -13066.052, Max-Change: 0.00034
Iteration: 419, Log-Lik: -13066.052, Max-Change: 0.00040
Iteration: 420, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 421, Log-Lik: -13066.052, Max-Change: 0.00033
Iteration: 422, Log-Lik: -13066.052, Max-Change: 0.00041
Iteration: 423, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 424, Log-Lik: -13066.052, Max-Change: 0.00034
Iteration: 425, Log-Lik: -13066.052, Max-Change: 0.00040
Iteration: 426, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 427, Log-Lik: -13066.052, Max-Change: 0.00033
Iteration: 428, Log-Lik: -13066.052, Max-Change: 0.00041
Iteration: 429, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 430, Log-Lik: -13066.052, Max-Change: 0.00034
Iteration: 431, Log-Lik: -13066.052, Max-Change: 0.00040
Iteration: 432, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 433, Log-Lik: -13066.052, Max-Change: 0.00033
Iteration: 434, Log-Lik: -13066.052, Max-Change: 0.00041
Iteration: 435, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 436, Log-Lik: -13066.052, Max-Change: 0.00034
Iteration: 437, Log-Lik: -13066.052, Max-Change: 0.00040
Iteration: 438, Log-Lik: -13066.052, Max-Change: 0.00049
Iteration: 439, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 440, Log-Lik: -13066.051, Max-Change: 0.00041
Iteration: 441, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 442, Log-Lik: -13066.051, Max-Change: 0.00034
Iteration: 443, Log-Lik: -13066.051, Max-Change: 0.00040
Iteration: 444, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 445, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 446, Log-Lik: -13066.051, Max-Change: 0.00041
Iteration: 447, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 448, Log-Lik: -13066.051, Max-Change: 0.00034
Iteration: 449, Log-Lik: -13066.051, Max-Change: 0.00040
Iteration: 450, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 451, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 452, Log-Lik: -13066.051, Max-Change: 0.00041
Iteration: 453, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 454, Log-Lik: -13066.051, Max-Change: 0.00034
Iteration: 455, Log-Lik: -13066.051, Max-Change: 0.00040
Iteration: 456, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 457, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 458, Log-Lik: -13066.051, Max-Change: 0.00041
Iteration: 459, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 460, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 461, Log-Lik: -13066.051, Max-Change: 0.00040
Iteration: 462, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 463, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 464, Log-Lik: -13066.051, Max-Change: 0.00040
Iteration: 465, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 466, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 467, Log-Lik: -13066.051, Max-Change: 0.00040
Iteration: 468, Log-Lik: -13066.051, Max-Change: 0.00049
Iteration: 469, Log-Lik: -13066.051, Max-Change: 0.00033
Iteration: 470, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 471, Log-Lik: -13066.050, Max-Change: 0.00049
Iteration: 472, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 473, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 474, Log-Lik: -13066.050, Max-Change: 0.00049
Iteration: 475, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 476, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 477, Log-Lik: -13066.050, Max-Change: 0.00048
Iteration: 478, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 479, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 480, Log-Lik: -13066.050, Max-Change: 0.00049
Iteration: 481, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 482, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 483, Log-Lik: -13066.050, Max-Change: 0.00048
Iteration: 484, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 485, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 486, Log-Lik: -13066.050, Max-Change: 0.00049
Iteration: 487, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 488, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 489, Log-Lik: -13066.050, Max-Change: 0.00048
Iteration: 490, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 491, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 492, Log-Lik: -13066.050, Max-Change: 0.00049
Iteration: 493, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 494, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 495, Log-Lik: -13066.050, Max-Change: 0.00048
Iteration: 496, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 497, Log-Lik: -13066.050, Max-Change: 0.00040
Iteration: 498, Log-Lik: -13066.050, Max-Change: 0.00049
Iteration: 499, Log-Lik: -13066.050, Max-Change: 0.00033
Iteration: 500, Log-Lik: -13066.050, Max-Change: 0.00040</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>EM cycles terminated after 500 iterations.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>

Calculating information matrix...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>fourpl_params <span class="ot">&lt;-</span> <span class="fu">coef</span>(fourpl_fit, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>,</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>fourpl_items <span class="ot">&lt;-</span> fourpl_params<span class="sc">$</span>items</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fourpl_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 a          b            g         u
reason.4  1.975112 -0.3394009 0.1103560321 0.9912975
reason.16 1.603067 -0.8560177 0.0004110258 0.9673521
reason.17 2.064785 -0.7469931 0.0007629951 0.9718849
reason.19 1.911800 -0.6231126 0.0005020762 0.9058245
letter.7  3.599069 -0.3507855 0.1257652136 0.8856107
letter.33 3.398542 -0.3096880 0.1338100363 0.8530054</code></pre>
</div>
</div>
<p>결과에서 마지막 열(즉, 상한 점근)이 이번에는 0이 아닌 것을 볼 수 있는데, 이는 추정에 4PL 모델을 사용했기 때문입니다. 대부분의 문항에서 상한 점근 모수가 1에 가깝지만 상한 점근이 더 낮은 문항이 몇 개 있습니다(예: letter.7, letter.33). 이러한 문항에 올바르게 응답할 수 있는 최대 확률은 잠재 특성이 높은 피험자의 경우에도 1에 근접하지 않습니다. 이전 모델에서 했던 것처럼 4PL 모델의 문항 모수가 ICC에 미치는 영향을 시각적으로 살펴볼 수도 있습니다. 다음 코드는 item 13 및 16에 대한 ICC 그래프를 생성하는 명령을 보여줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fourpl_fit, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">which.items =</span> <span class="fu">c</span>(<span class="dv">13</span>, <span class="dv">16</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="irt-모델에서-능력-추정" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="irt-모델에서-능력-추정"><span class="header-section-number">5.4</span> IRT 모델에서 능력 추정</h2>
<p>특정 IRT 모델을 사용하여 문항 모수를 추정하고 나면 다음 단계는 <span class="math inline">\(N\)</span>개의 문항에 응답한 각 피험자의 잠재 특성 추정치를 구하는 것입니다. 잠재 특성 수준이 <span class="math inline">\(\theta_j\)</span>인 사람의 <span class="math inline">\(N\)</span>개 문항에 대한 응답 벡터가 주어지면 IRT 모델의 모수(이 경우 3PL)가 주어진 각 문항에 대해 정답 확률인 <span class="math inline">\(P(\theta_j, a_i, b_i, c_i)\)</span>와 오답 확률인 <span class="math inline">\(Q(\theta_j, a_i, b_i, c_i) = 1 - P(\theta_j, a_i, b_i, c_i)\)</span>를 계산할 수 있습니다. 응답 패턴에 있는 문항의 확률을 곱하면 다음과 같이 <span class="math inline">\(N\)</span>개 문항에 대한 결합 우도 함수를 구할 수 있습니다.</p>
<p><span class="math display">\[
L(\theta_j)=\prod_{i=1}^N P_i(\theta_j, a_i, b_i, c_i)^{x_i}Q_i(\theta_j, a_i, b_i, c_i)^{1-x_i}
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(x_i\)</span>는 문항 <span class="math inline">\(i\)</span>에 대한 피험자 <span class="math inline">\(j\)</span>의 점수입니다(0 또는 1 중 하나).</li>
</ul>
<p>각각의 고유한 응답 패턴에 대해 단일 우도 함수가 있습니다. 아래에서는 결합 우도 함수를 통해 잠재 특성을 추정하는 데 널리 사용되는 세 가지 방법을 설명합니다.</p>
<ol type="1">
<li><p>최대 우도 추정(MLE): 이 방법은 관찰된 피험자의 응답 패턴과 문항 모수가 주어졌을 때 가장 가능성이 높은 잠재 특성을 찾는 것을 목표로 합니다. 즉, MLE는 우도 함수를 최대화하는 추정치 <span class="math inline">\(\theta_j\)</span>를 찾습니다.</p></li>
<li><p>최대 사후 추정(MAP): MLE 접근 방식의 일반적인 변형은 베이지안 모달 추정 절차로, 최대 사후 추정 또는 MAP라고도 하며, 여기서 결합 우도 함수에 가정된 모집단 분포를 나타내는 추가 곡선을 곱합니다. MAP는 이 사후 분포의 최빈값을 잠재 특성의 최종 추정치로 계산합니다.</p></li>
<li><p>사후 기대치(EAP): MAP 접근 방식의 변형은 사후 분포의 최빈값 대신 평균을 사용하는 사후 기대치 또는 EAP입니다.</p></li>
</ol>
<p>베이지안 방법의 주요 장점은 피험자가 정답 또는 오답만 있는 경우에도 잠재 특성을 추정할 수 있는 반면, MLE 접근법은 응답 벡터에 변동성이 0인 경우 잠재 특성 추정치를 제공할 수 없다는 것입니다. 베이지안 방법을 사용하면 가정된 모집단 분포를 통해 추정된 모수에 편향이 도입됩니다. mirt 패키지는 fscores 함수를 통해 MLE, MAP 및 EAP 접근법을 사용하여 잠재 특성을 추정할 수 있습니다. 또한 fscores 함수는 합계 점수(Thissen, Pommerich, Billeaud, &amp; Williams, 1995) 및 가중된 우도 추정(Warm, 1989)을 위해 EAP를 사용할 수 있습니다. MLE, MAP 및 EAP는 연구자 및 실무자가 일반적으로 사용하므로 아래에서는 이러한 방법에만 초점을 맞춥니다.</p>
<p>다음 예에서는 SAPA 데이터 세트와 이 장의 앞부분에 적합했던 2PL 모델의 문항 모수를 사용하여 MLE, MAP 및 EAP 접근법을 사용하여 잠재 특성을 추정합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>latent_mle <span class="ot">&lt;-</span> <span class="fu">fscores</span>(twopl_fit, <span class="at">method =</span> <span class="st">"ML"</span>,</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">full.scores =</span> <span class="cn">TRUE</span>, <span class="at">full.scores.SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The following factor score estimates failed to converge successfully:
    368,614,996</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>latent_map <span class="ot">&lt;-</span> <span class="fu">fscores</span>(twopl_fit, <span class="at">method =</span> <span class="st">"MAP"</span>,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">full.scores =</span> <span class="cn">TRUE</span>, <span class="at">full.scores.SE =</span> <span class="cn">TRUE</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>latent_eap <span class="ot">&lt;-</span> <span class="fu">fscores</span>(twopl_fit, <span class="at">method =</span> <span class="st">"EAP"</span>,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">full.scores =</span> <span class="cn">TRUE</span>, <span class="at">full.scores.SE =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>처음 6명의 피험자에 대한 MLE 잠재 특성 추정치를 보려면 latent_mle과 함께 head 함수를 사용하면 됩니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(latent_mle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              F      SE_F
[1,] -1.7233250 0.5971554
[2,] -0.7311886 0.4026671
[3,] -0.6771320 0.3986155
[4,] -1.3901749 0.5032752
[5,] -0.7127487 0.4012232
[6,]  1.8175250 0.5662481</code></pre>
</div>
</div>
<p>결과에서 첫 번째 열(F1)은 추정된 잠재 특성을 나타내고 두 번째 열(즉, SE_F1)은 표준 오차를 나타냅니다. 세 가지 추정 방법을 비교하기 위해 첫 번째 열에 있는 추정된 잠재 특성을 세 가지 추정 방법에서 추출하고 이를 latent라는 하나의 데이터 프레임에 결합합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>latent <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">MLE =</span> latent_mle[ ,<span class="dv">1</span>],</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">MAP =</span> latent_map[ ,<span class="dv">1</span>],</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">EAP =</span> latent_eap[ ,<span class="dv">1</span>])</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(latent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         MLE        MAP        EAP
1 -1.7233250 -1.3365328 -1.4067370
2 -0.7311886 -0.6307885 -0.6505215
3 -0.6771320 -0.5854772 -0.6028731
4 -1.3901749 -1.1338101 -1.1870565
5 -0.7127487 -0.6153768 -0.6343019
6  1.8175250  1.4356287  1.4935857</code></pre>
</div>
</div>
<p>세 가지 추정 방법이 비슷한 결과를 제공하며, MAP와 EAP의 추정치가 거의 동일하다는 것을 알 수 있습니다. 앞서 언급했듯이, 모든 응답이 정답이거나 오답인 경우 MLE 방법은 잠재 특성을 추정할 수 없습니다. SAPA 데이터 세트에는 모든 문항에 정답(예: 피험자 73, 89, 103)이나 오답(예: 피험자 105)으로 답한 피험자가 여러 명 있으므로 MLE는 이러한 피험자에 대한 잠재 특성을 추정할 수 없습니다. 아래에는 latent 데이터 프레임에서 이러한 피험자의 추정치를 출력하여 이를 보여줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>latent[<span class="fu">c</span>(<span class="dv">73</span>, <span class="dv">89</span>, <span class="dv">103</span>, <span class="dv">105</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     MLE       MAP       EAP
73   Inf  1.985339  2.096258
89   Inf  1.985339  2.096258
103  Inf  1.985339  2.096258
105 -Inf -1.864351 -1.980879</code></pre>
</div>
</div>
<p>잠재 특성 추정치 간의 기술통계 및 상관관계를 계산하려면 먼저 is.finite 함수를 사용하여 MLE 열에서 Inf 또는 -Inf 점수가 있는 피험자를 제거하고 나머지 데이터를 latent_est로 저장합니다. 결과 데이터 프레임에는 MLE, MAP 및 EAP 방법에서 유효한 잠재 특성 추정치가 있는 1461명의 피험자가 포함됩니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>latent_est <span class="ot">&lt;-</span> latent[<span class="fu">is.finite</span>(latent<span class="sc">$</span>MLE), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>다음으로 summary 및 apply 함수를 사용하여 기술통계를 얻습니다. 다시 한 번 설명하자면, apply 함수를 사용하려면 데이터, 함수를 적용하려는 데이터의 한계(행의 경우 1, 열의 경우 2), 적용하려는 함수를 지정해야 합니다. 아래에서는 apply 함수를 사용하여 추정치의 요약 통계 및 표준 편차(sd 함수를 통해)를 계산하고 데이터에서 열로 정렬되어 있으므로 2를 지정합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(latent_est, <span class="dv">2</span>, summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 MLE         MAP          EAP
Min.    -2.439114424 -1.62922178 -1.725578545
1st Qu. -0.689406667 -0.59580053 -0.613718783
Median  -0.025201555 -0.02195921 -0.019611185
Mean     0.002659148  0.00357282  0.001146392
3rd Qu.  0.664415606  0.57240513  0.584675590
Max.     2.590186515  1.76241571  1.851380586</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(latent_est, <span class="dv">2</span>, sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      MLE       MAP       EAP 
1.0112851 0.8021994 0.8345610 </code></pre>
</div>
</div>
<p>세 가지 추정 방법의 잠재 특성의 평균과 중앙값은 매우 유사합니다. 그러나 MLE 접근법의 잠재 특성 추정치의 범위와 표준 편차는 다른 두 방법의 추정치보다 큽니다. 이는 MAP 및 EAP 방법이 추정 과정에서 잠재 특성 분포를 이전 평균으로 정의된 모집단 평균으로 축소하는 것으로 알려져 있기 때문에 예상되는 결과입니다(Reise &amp; Revicki, 2014).</p>
<p>다음으로 cor 함수를 사용하여 잠재 특성 추정치 간의 상관관계를 계산합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(latent_est)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          MLE       MAP       EAP
MLE 1.0000000 0.9973045 0.9978970
MAP 0.9973045 1.0000000 0.9999447
EAP 0.9978970 0.9999447 1.0000000</code></pre>
</div>
</div>
<p>잠재 특성 추정치 간의 상관관계가 매우 높다는 것은 세 가지 추정 방법 간의 높은 일치도를 나타냅니다. 그러나 MAP 및 EAP 방법을 사용할 때 강력한 사전 분포를 포함하면 사후 추정치에 영향을 미칠 수 있으므로 항상 그런 것은 아닙니다. 세 가지 추정 방법 간의 연관성을 더 잘 이해하기 위해 pair 함수를 사용하여 각 방법에 대해 추정된 잠재 특성의 산점도 행렬을 생성합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(latent_est)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>그림 5.13은 MAP 방법과 EAP 방법의 잠재 특성 추정치가 높은 상관관계와 선형적 연관성을 보이는 반면, MLE 방법의 잠재 특성 추정치는 MAP 방법과 약간 비선형적인 관계를 보여줍니다. 비선형성은 특히 분포의 꼬리 부분에서 두드러집니다.</p>
<p>마지막으로, MLE, MAP 및 EAP 방법으로 추정된 잠재 특성 값 간의 차이에 대한 표본 표준 편차, 즉 평균 제곱 편차근(RMSD)를 계산합니다. RMSD는 다음과 같이 계산할 수 있습니다.</p>
<p><span class="math display">\[
RMSD=\sqrt{\sum_{j=1}^N (\hat\theta_{1j}-\hat\theta_{2j})^2 \over N}
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(\hat\theta_{1j}\)</span> 및 <span class="math inline">\(\hat\theta_{2j}\)</span>는 첫 번째 및 두 번째 추정 방법에서 피험자 <span class="math inline">\(j\)</span>에 대한 잠재 특성 추정치입니다.</li>
</ul>
<p>추정 방법의 순서(예: MLE-MAP 대 MAP-MLE)는 방정식에서 이 차이를 제곱하기 때문에 RMSD 값에 영향을 미치지 않는다는 점에 유의하세요. hemp에서 rmsd 함수를 사용하여 RMSD를 계산할 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rmsd</span>(latent_est<span class="sc">$</span>MLE, latent_est<span class="sc">$</span>MAP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03492328</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rmsd</span>(latent_est<span class="sc">$</span>MLE, latent_est<span class="sc">$</span>EAP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05782215</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rmsd</span>(latent_est<span class="sc">$</span>MAP, latent_est<span class="sc">$</span>EAP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09274544</code></pre>
</div>
</div>
<p>결과는 MLE 방법과 MAP 방법의 잠재 특성 추정치 간의 차이가 가장 작은 반면, MAP 방법과 EAP 방법의 잠재 특성 추정치 간의 차이가 가장 크다는 것을 나타냅니다.</p>
</section>
<section id="모델-진단" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="모델-진단"><span class="header-section-number">5.5</span> 모델 진단</h2>
<p>이 장의 시작 부분에서 IRT의 가정(예: 단일차원성, 지역 독립성, 문항 모수의 불변성)에 대해 간략하게 소개했습니다. 이러한 가정이 어느 정도 충족되면 다음 단계는 특정 IRT 모델을 선택하여 응답 데이터에 적용하는 것입니다. 모든 통계적 노력에서와 마찬가지로 선택한 IRT 모델과 문항 응답 데이터 간에 불일치가 관찰될 수 있습니다. 선택한 IRT 모델의 근거를 제공하려면 이러한 잠재적 불일치를 식별하는 데 도움이 되는 모델 진단을 수행하는 것이 중요합니다.</p>
<p>IRT에서 모델 진단은 문항, 개인 및 모델 수준(즉, 모델의 적합도)의 세 가지 수준에서 검토할 수 있습니다. 다음 섹션에서는 IRT에서 모델 진단 방법에 대해 간략하게 설명하고 mirt 패키지를 사용하여 이러한 방법의 사용을 시연합니다. IRT의 모델 진단에 대한 자세한 논의는 Maydeu-Olivares(2013), Swaminathan, Hambleton, Rogers(2006) 및 기타 리소스를 검토해 보시기 바랍니다.</p>
<section id="문항-적합" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="문항-적합"><span class="header-section-number">5.5.1</span> 문항 적합</h3>
<p>IRT에서 문항 적합도를 평가하는 방법에는 일반적으로 문항 적합도 통계와 문항 적합도의 그래픽 분석이라는 두 가지 접근 방식이 있습니다. 가장 자주 사용되는 문항 적합도 통계로는 signed <span class="math inline">\(\chi^2\)</span> 검사(Orlando &amp; Thissen, 2000), Bock’s <span class="math inline">\(\chi^2\)</span> 방법(Bock, 1972), Yen의 <span class="math inline">\(Q1\)</span> 통계(Yen, 1981), <span class="math inline">\(G2\)</span> 통계(McKinley &amp; Mills, 1985), 특히 Rasch 계열의 IRT 모델에 대한 infit 및 outfit 통계가 있습니다. Bock의 <span class="math inline">\(\chi^2\)</span> 방법, Yen의 <span class="math inline">\(Q1\)</span> 통계, <span class="math inline">\(G2\)</span> 통계와 같은 일부 방법은 경험적 확률과 모델 예측 확률을 비교하는 데 의존합니다. 이러한 방법의 경우 선택한 IRT 모델이 데이터에 적절히 부합한다는 귀무가설 하에서 유의성 검정을 사용할 수 있습니다. 일반적인 형식에서 이분 문항에 대한 <span class="math inline">\(\chi^2\)</span> 문항 적합도 통계는 다음과 같이 계산할 수 있습니다.</p>
<p><span class="math display">\[
\chi^2=\sum_{j=1} ^J N_j{(O_j-E_j) ^2 \over E_j(1-E_j)}
\]</span></p>
<ul>
<li><p>여기서 <span class="math inline">\(j\)</span>는 잠재 특성 구간(예: \theta = -2 ~ \theta = -1.5)</p></li>
<li><p><span class="math inline">\(O_j\)</span>는 잠재 특성 구간 <span class="math inline">\(j\)</span>에서 관찰된(즉, 경험적) 정답을 맞힐 확률</p></li>
<li><p><span class="math inline">\(E_j\)</span>는 적합된 IRT 모델을 기반으로 잠재 특성 구간 <span class="math inline">\(j\)</span>에서 기대된(즉, 이론적) 정답을 맞힐 확률</p></li>
<li><p><span class="math inline">\(N_j\)</span>는 잠재 특성 구간 <span class="math inline">\(j\)</span>에 위치한 피험자 수입니다.</p></li>
</ul>
<p>Bock의 <span class="math inline">\(\chi^2\)</span> 방법에서는 각 잠재 특성 구간은 동일한 크기를 가지며 각 구간의 잠재 특성 중앙값을 사용하여 정답 예상 비율을 계산합니다. 이와 대조적으로, Yen의 Q1 통계에서는 동일한 빈도를 가진 10개의 잠재 특성 구간이 필요하며, 예상 확률은 정답 확률의 평균이 됩니다. 두 통계의 자유도는 모두 <span class="math inline">\(J-m\)</span>으로 같으며, 여기서 <span class="math inline">\(m\)</span>은 IRT 모델에서 문항 모수의 수입니다(예: 2PL 모델의 경우 m = 2).</p>
<p>Orlando와 Thissen(2000)은 유의미한 문항 부적합이 존재하면 잠재 특성 추정치가 편향되어 <span class="math inline">\(\chi^2\)</span> 방법의 문항 적합도 검사에 영향을 미칠 수 있다고 주장했습니다. 따라서 Orlando와 Thissen(2000)은 잠재 특성 추정치 대신 원점수에 따라 피험자를 그룹화할 것을 제안했습니다. 이 대체 방법을 signed <span class="math inline">\(\chi^2\)</span> 통계라고 하며, <span class="math inline">\(S - X^2\)</span> 통계라고도 합니다. 주어진 문항에 대한 signed <span class="math inline">\(\chi^2\)</span> 통계는 다음과 같이 작성할 수 있습니다.</p>
<p><span class="math display">\[
S-X^2=\sum_{k} ^{n-1} N_k{(O_k-E_k) ^2 \over E_k(1-E_k)}
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(n\)</span>은 검사의 문항 수이고, <span class="math inline">\(k\)</span>는 원점수(즉, 정답 수)이며, 다른 요소는 방정식 5.11의 요소와 동일합니다.</li>
</ul>
<p>signed <span class="math inline">\(\chi^2\)</span> 통계의 자유도는 <span class="math inline">\((n - 1) - m\)</span> 이며, 여기서 <span class="math inline">\(m\)</span>은 다시 IRT 모형의 문항 모수 수입니다.</p>
<p><span class="math inline">\(\chi^2\)</span> 문항 적합도 통계와 달리 <span class="math inline">\(G2\)</span> 통계는 우도비 검정을 기반으로 합니다. 방정식 5.11의 동일한 요소를 사용하여 <span class="math inline">\(G2\)</span> 통계는 다음과 같이 계산할 수 있습니다.</p>
<p><span class="math display">\[
G^2=2\sum_{j=1} ^{J} N_j(O_j log{O_j \over E_j} + (1 - O_j)log{1 - O_j \over 1 - E_j})
\]</span></p>
<p><span class="math inline">\(G2\)</span> 통계의 자유도는 <span class="math inline">\(J - m\)</span>과 같습니다. 앞서 언급했듯이, Bock의 <span class="math inline">\(\chi^2\)</span> 통계, Yen의 <span class="math inline">\(Q1\)</span> 통계 및 <span class="math inline">\(G2\)</span> 통계는 문항이 IRT 모델에 적절하게 적합하다는 영가설 하에서 작동합니다. 따라서 특정 문항에 대한 영가설을 기각한다는 것은 해당 문항이 모델에 적절하게 맞지 않을 수 있음을 의미합니다.</p>
<p>다음 예에서는 mirt 패키지의 itemfit 함수를 사용하여 Rasch 모델의 문항 모수에 대한 문항 적합도 통계를 검사합니다. itemfit 함수에서 fit_stats = c(“S-X2”, “G2”)를 지정하여 <span class="math inline">\(S - X^2\)</span> 및 <span class="math inline">\(G2\)</span> 문항 적합도 통계를 얻습니다. impute 옵션은 결측 데이터가 있을 때 수행할 대체 횟수를 지정합니다. SAPA 데이터 세트에 결측 응답이 여러 개 있으므로 impute = 10을 사용하여 10개의 대체된 데이터 세트를 만듭니다. 결과를 rasch_itemfit으로 저장하고 head 함수를 사용하여 결과의 처음 여섯 행을 출력합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>rasch_itemfit <span class="ot">&lt;-</span> <span class="fu">itemfit</span>(rasch_fit,</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">fit_stats =</span> <span class="fu">c</span>(<span class="st">"S_X2"</span>, <span class="st">"G2"</span>),</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Sample size after row-wise response data removal: 1523</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rasch_itemfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       item     G2 df.G2 RMSEA.G2  p.G2   S_X2 df.S_X2 RMSEA.S_X2 p.S_X2
1  reason.4 53.846     9    0.057 0.000 20.604      12      0.022  0.056
2 reason.16 30.648     9    0.040 0.000 10.862      12      0.000  0.541
3 reason.17 47.332     9    0.053 0.000 19.907      12      0.021  0.069
4 reason.19 28.971     9    0.038 0.001 26.680      12      0.028  0.009
5  letter.7 29.814     9    0.039 0.000 12.495      12      0.005  0.407
6 letter.33 15.784     9    0.022 0.072 26.988      13      0.027  0.012</code></pre>
</div>
</div>
<p>결과에서 G2, df.G2 및 p.G2 열은 <span class="math inline">\(G2\)</span> 통계, <span class="math inline">\(G2\)</span> 통계의 자유도 및 <span class="math inline">\(G2\)</span> 통계의 p값을 나타냅니다. 마찬가지로 S_X2, df.S_X2 및 p.S_X2 열은 <span class="math inline">\(S - X^2\)</span> 통계, <span class="math inline">\(S - X^2\)</span> 통계의 자유도 및 <span class="math inline">\(S - X^2\)</span> 통계의 p값을 나타냅니다. <span class="math inline">\(\alpha\)</span> = .05를 유의 수준으로 사용하는 경우 특정 문항에 대한 p값이 .05 미만이면 해당 문항이 Rasch 모형에 맞지 않음을 나타냅니다.</p>
<p>itemfit 함수는 선택한 IRT 모델과 응답 데이터 간의 전반적인 불일치 정도를 정량화하는 <span class="math inline">\(Z_h\)</span>, infit 및 outfit 통계와 같은 다른 문항 적합도 측정값도 제공합니다. infit 및 outfit 통계는 Rasch 모델 제품군(예: Rasch 모델, 부분 점수 모델 및 등급 척도 모델)에 대해서만 사용할 수 있습니다. 다음 예에서는 fit_stats = c(“Zh”, “infit”)를 사용하여 Rasch 모델에 대한 <span class="math inline">\(Z_h\)</span>, infit 및 outfit 통계를 구하는 방법을 보여 줍니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemfit</span>(rasch_fit, </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">fit_stats =</span> <span class="fu">c</span>(<span class="st">"Zh"</span>, <span class="st">"infit"</span>), </span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Sample size after row-wise response data removal: 1523</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        item     Zh outfit z.outfit infit z.infit
1   reason.4  4.937  0.777   -4.604 0.865  -5.118
2  reason.16  2.928  0.836   -2.723 0.911  -2.983
3  reason.17  5.250  0.749   -4.349 0.836  -5.689
4  reason.19  3.404  0.869   -2.795 0.904  -3.681
5   letter.7  4.642  0.819   -4.085 0.874  -4.998
6  letter.33  2.969  0.903   -2.267 0.918  -3.275
7  letter.34  5.179  0.836   -3.563 0.850  -5.911
8  letter.58  3.873  0.841   -3.963 0.901  -3.993
9  matrix.45  0.304  0.969   -0.738 0.995  -0.183
10 matrix.46  0.622  0.963   -0.853 0.985  -0.604
11 matrix.47  2.869  0.866   -2.856 0.926  -2.819
12 matrix.55 -2.507  1.101    2.021 1.068   2.406
13  rotate.3  3.067  0.975   -0.231 0.834  -4.185
14  rotate.4  4.517  0.782   -2.685 0.803  -5.364
15  rotate.6  3.541  0.858   -2.392 0.878  -4.042
16  rotate.8  2.103  0.894   -1.086 0.888  -2.666</code></pre>
</div>
</div>
<p>문헌에는 <span class="math inline">\(Z_h\)</span>, infit 및 outfit 통계치를 해석하기 위한 컷오프 값과 관련하여 다양한 권장 사항이 있습니다. 이 장에서는 이러한 권장 사항에 대한 자세한 내용은 다루지 않습니다. 일반적으로 문항에 대한 결정을 문항 적합도 통계에만 근거하여 내리는 것은 권장하지 않습니다. 이러한 통계는 종종 일치하지 않는 경우가 많으므로(위의 reason.19 문항에서 볼 수 있듯이) 주의해서 사용해야 합니다. 따라서 위에 제시된 통계는 독자들에게 통계를 알리기 위한 것이며 교훈적인 목적으로만 표시됩니다.</p>
<p>itemfit 함수는 문항에 대한 경험적 그래프를 만드는 데도 사용할 수 있으며, 이는 문항 적합도 통계보다 문항 부적합을 감지하는 데 더 유용할 수 있습니다. 다음 예에서는 SAPA 데이터 집합의 item 1에 대한 경험적 그래프를 만듭니다. 이 그래프는 경험적 데이터 요소와 Rasch 모델에 대한 이론적 ICC를 함께 보여줍니다. 경험적 데이터가 ICC에 가까울수록 문항 적합도가 더 좋으며, 그림 5.14에 따르면 문항 1의 경우가 이에 해당합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemfit</span>(rasch_fit, <span class="at">empirical.plot =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="피험자-적합도" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="피험자-적합도"><span class="header-section-number">5.5.2</span> 피험자 적합도</h3>
<p>IRT의 맥락에서, 피험자 적합도는 피험자의 반응 패턴과 응답 데이터를 모델링하기 위해 선택한 IRT 모델 간의 정렬을 의미합니다. 피험자 적합도 지수는 피험자 수준에서 선택한 모델의 타당성과 추정된 잠재 특성 수준의 유의성을 평가하는 데 사용됩니다(Embretson &amp; Reise, 2000). 문헌에는 IRT 모델에 대해 다양한 피험자 적합도 지수가 제안되어 있습니다. 이 섹션에서는 특히 Drasgow, Levine, Williams(1985)가 처음 제안한 표준화된 적합도 지수인 <span class="math inline">\(Z_h\)</span>에 초점을 맞춥니다. 잠재 특성 수준 <span class="math inline">\(\theta_j\)</span>를 가진 피험자 <span class="math inline">\(j\)</span>에 대한 <span class="math inline">\(Z_h\)</span> 통계는 다음과 같이 계산할 수 있습니다.</p>
<p><span class="math display">\[
Z_h={\sum [logL|\theta_j-\sum E(LogL|\theta_j)] \over \sqrt(\sum V(LogL|\theta_j))}
\]</span></p>
<p>여기서 <span class="math inline">\(LogL\)</span>은 피험자 <span class="math inline">\(j\)</span>의 반응 패턴에 대한 로그 확률 값이고, <span class="math inline">\(E(LogL|\theta_j)\)</span>는 <span class="math inline">\(\theta_j\)</span>에 조건부 로그 확률의 표집 분포에 대한 평균 로그 확률 값이며, <span class="math inline">\(V(LogL|\theta_j\)</span>)는 로그 확률 값의 표집 분포의 분산입니다. <span class="math inline">\(Z_h\)</span>는 표준 정규 분포를 따르는 표준화된 통계이므로 피험자의 반응 패턴이 선택한 IRT 모델과 일치하는 경우 <span class="math inline">\(Z_h\)</span>의 기대값은 0입니다. 큰 음의 <span class="math inline">\(Z_h\)</span> 값(예: <span class="math inline">\(Z_h &lt; -2\)</span>)은 피험자 부적합을 나타냅니다. 큰 양의 <span class="math inline">\(Z_h\)</span> 값은 피험자의 반응 패턴에 대한 우도가 선택한 IRT 모델에 따라 예측된 우도보다 높음을 나타내며(Embretson &amp; Reise, 2000), 이는 잠재 특성 추정에도 문제가 될 수 있습니다.</p>
<p>다음 예에서는 mirt 패키지의 personfit 함수를 사용하여 SAPA 데이터 세트에서 피험자의 응답 패턴에 대한 <span class="math inline">\(Z_h\)</span> 통계를 얻습니다. personfit 함수를 사용하려면 반응 데이터에 결측치가 없어야 합니다. 따라서 먼저 SAPA 데이터 세트에서 결측치가 있는 피험자를 제거하고, 전체 데이터 세트를 사용하여 Rasch 모델을 다시 적합하고, 피험자 적합도 통계를 계산한 다음, 처음 몇 명의 피험자에 대한 적합도 통계를 출력합니다. 이번에는 mirt가 로그 우도 변경에 대한 정보를 R 콘솔에 출력하지 못하도록 verbose = FALSE 인수를 지정합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>SAPA_nomiss <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(SAPA)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>rasch_mod <span class="ot">&lt;-</span> <span class="st">"F = 1 - 16"</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>rasch_fit <span class="ot">&lt;-</span> <span class="fu">mirt</span>(<span class="at">data =</span> SAPA_nomiss, <span class="at">model =</span> rasch_mod,</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">itemtype =</span> <span class="st">"Rasch"</span>, <span class="at">SE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>rasch_personfit <span class="ot">&lt;-</span> <span class="fu">personfit</span>(rasch_fit)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rasch_personfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     outfit   z.outfit     infit    z.infit         Zh
1 1.2568894  0.5629416 1.0167398  0.1760094 -0.2366800
2 1.1913429  0.5135685 1.0413377  0.2503287 -0.3039963
3 0.7145810 -0.5621469 0.8733417 -0.5890664  0.6562832
4 0.5611157 -0.3596852 0.7938685 -0.4142847  0.5659128
5 0.7357641 -0.5034390 0.8989894 -0.4512733  0.5565218
6 0.4846891 -0.6398586 0.7733773 -0.4545129  0.6154778</code></pre>
</div>
</div>
<p>결과에서 처음 네 개의 열인 outfit, z.outfit, infit, z.infit은 각각 infit 및 outfit 피험자 적합도 통계에 해당합니다. 마지막 열인 Zh는 <span class="math inline">\(Z_h\)</span> 통계를 기반으로 피험자 적합도를 검사하는 데 사용할 수 있습니다. 결과는 처음 6명의 피험자의 반응 패턴이 <span class="math inline">\(Z_h\)</span> 통계가 -2보다 크기 때문에 Rasch 모델과 일치한다는 것을 보여줍니다. hist 함수를 사용하여 <span class="math inline">\(Z_h\)</span> 통계 분포의 히스토그램을 쉽게 만들 수도 있습니다. abline(v = -2, lwd = 2, lty = 2)을 사용하여 피험자 부적합이 있는 피험자를 식별하기 위한 기준점으로 Zh = -2 에 수직 점선을 그립니다. 그림 5.15는 대부분의 피험자에 대한 <span class="math inline">\(Z_h\)</span> 통계가 -2보다 크다는 것을 보여 주며, 이는 대부분의 피험자가 선택된 IRT 모델에 적합하다는 것을 의미합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(rasch_personfit<span class="sc">$</span>Zh, <span class="at">xlab=</span><span class="st">"Zh Statistic"</span>)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chap05_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>마지막으로 rownames 함수를 사용하여 <span class="math inline">\(Z_h\)</span> 통계가 -2보다 작은 피험자를 하위 세트로 만들어 출력합니다. nrow 함수를 사용하여 Rasch 모델에 맞지 않는 피험자가 40명임을 알 수 있습니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>rasch_misfits <span class="ot">&lt;-</span> <span class="fu">subset</span>(rasch_personfit, Zh <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(rasch_misfits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "41"   "63"   "65"   "98"   "214"  "227"  "268"  "269"  "275"  "354" 
[11] "368"  "393"  "411"  "445"  "466"  "470"  "503"  "524"  "534"  "537" 
[21] "560"  "566"  "597"  "619"  "668"  "684"  "735"  "804"  "806"  "818" 
[31] "849"  "889"  "946"  "1017" "1092" "1109" "1326" "1337" "1394" "1464"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(rasch_misfits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40</code></pre>
</div>
</div>
</section>
<section id="모델-선택" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="모델-선택"><span class="header-section-number">5.5.3</span> 모델 선택</h3>
<p>IRT에서 모델 선택은 평가의 기반이 되는 이론과 반응 데이터의 특성에 따라 달라집니다. 예를 들어, 모든 문항의 변별도가 동일하다고 가정하면 다른 모델(예: 2PL 및 3PL)보다 1PL 모델(또는 Rasch 모델)을 사용하는 것이 더 좋습니다. 그러나 문항의 변별도 모수가 크게 다를 경우 문항 변별도 모수를 모든 문항에서 동일하도록 제한하는 것이 최선의 결정이 아닐 수 있습니다. 따라서 동일한 데이터에 서로 다른 IRT 모델을 적용하고 이러한 모델의 적합도를 비교할 수 있습니다. 단일차원 IRT 모델에서 이 비교는 여러 가지 방법으로 수행할 수 있습니다. 1PL, 2PL 및 3PL IRT 모델은 내재된 것으로 간주되므로(예: 변별도 모수가 문항 전체에서 동일하도록 제한하는 경우 1PL은 2PL 내에 내재되고, 의사 추측도 모수가 문항 전체에서 0이라는 추가 제약을 하는 경우 3PL 안에 내재됨) 모델의 전체 적합도를 비교하기 위해 확률 기반 통계를 사용할 수 있습니다. mirt 패키지에서 모델 비교는 anova 함수를 사용하여 수행할 수 있습니다.</p>
<p>다음 예에서는 SAPA 데이터 세트에 대해 이전에 적합화된 모델을 사용하여 모델 비교를 수행하는 방법을 보여 줍니다. 첫 번째 비교는 1PL 모델과 2PL 모델 간의 비교입니다. 모델 적합도와 관련하여 2PL 모델이 1PL 모델에 비해 유의미한 개선을 제공하는지 알고 싶습니다. 앞서 1PL 모델과 2PL 모델을 적합하고 그 결과를 onepl_fit 및 twopl_fit으로 저장했습니다. 두 모델을 비교하기 위해 anova 함수를 사용합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(onepl_fit, twopl_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               AIC    SABIC       HQ      BIC    logLik     X2 df p
onepl_fit 26566.50 26603.10 26600.23 26657.11 -13266.25            
twopl_fit 26464.79 26533.69 26528.28 26635.34 -13200.40 131.71 15 0</code></pre>
</div>
</div>
<p>여러 가지 모델 적합도 지수인 AIC, AICc(표본 크기 보정 AIC), SABIC 및 BIC가 출력에 표시됩니다. 이러한 적합도 지수가 작을수록 모델이 데이터에 더 잘 맞는다는 의미입니다. 결과에서 모든 적합도 지수가 2PL 모델이 더 작다는 것을 알 수 있으며, 이는 2PL 모델이 1PL 모델보다 SAPA 데이터 집합에 더 잘 맞는다는 것을 의미합니다. 또한 anova 함수는 두 모델의 로그 우도 값을 기반으로 우도비 검정을 수행합니다. 두 모델의 로그 우도 값의 절대 차이는 두 모델 간에 모델 적합도에 차이가 없다는 영가설 하에서 두 모델 간의 추정된 모수 수 차이와 동일한 자유도를 갖는 카이제곱(<span class="math inline">\(\chi^2\)</span>) 분포를 갖습니다. 즉, 모수가 더 많은 모델은 모수가 더 적은 모델보다 데이터에 더 잘 맞는 것으로 가정합니다. 두 통계의 <span class="math inline">\(\chi^2\)</span> 에 대한 p값이 .05 미만인 경우(사실상 <span class="math inline">\(\alpha = . 05\)</span> 사용), 더 복잡한 모델이 더 단순한 모델보다 더 잘 맞는다고 결론을 내릴 수 있습니다.</p>
<p>결과에서 <span class="math inline">\(\chi_{15}^2 = 131.71, p &lt; .001\)</span>을 볼 수 있는데, 이는 2PL 모델이 SAPA 데이터 세트에 대해 1PL 모델보다 더 잘 맞는다는 것을 의미합니다. 이 결과는 1PL 모델보다 2PL 모델을 선호하는 모델 적합도 지수와 일치합니다. 다음 단계에서는 2PL 모델과 3PL 모델의 적합도를 비교합니다. 이 비교에서는 모델에 의사 추측도 모수를 포함하면 모델 적합도가 향상되는지 여부를 테스트합니다. 모든 모델 적합도 지수는 3PL 모델에서 더 작으며, 이는 2PL 모델보다 3PL 모델을 선호합니다. 우도비 검정( <span class="math inline">\(\chi^2_{16} = 160.058, p &lt; .001)\)</span>은 통계적으로 유의미하며, 이는 3PL 모델이 2PL 모델에 비해 모델 적합도가 통계적으로 유의미하게 개선되었음을 의미합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(twopl_fit, threepl_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 AIC    SABIC       HQ      BIC    logLik      X2 df p
twopl_fit   26464.79 26533.69 26528.28 26635.34 -13200.40             
threepl_fit 26336.74 26440.08 26431.96 26592.56 -13120.37 160.058 16 0</code></pre>
</div>
</div>
<p>마지막 비교는 3PL 모델과 4PL 모델 간의 비교입니다. 결과는 다시 한 번 더 복잡한 모델(즉, 4PL 모델)이 덜 복잡한 모델보다 SAPA 데이터 세트에 더 잘 맞는다는 것을 시사합니다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(threepl_fit, fourpl_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 AIC    SABIC       HQ      BIC    logLik      X2 df p
threepl_fit 26336.74 26440.08 26431.96 26592.56 -13120.37             
fourpl_fit  26260.10 26397.89 26387.07 26601.20 -13066.05 108.636 16 0</code></pre>
</div>
</div>
<p>모수가 많은 모델이 모수가 적은 모델보다 데이터에 더 잘 맞는 경향이 있다는 점에 유의해야 합니다. 따라서 전체 모델 적합도의 비교가 항상 어떤 모델을 선택해야 하는지에 대한 올바른 결정으로 이어지지는 않을 수 있습니다. 앞서 설명했듯이, 모델 선택은 단순히 모델 적합도 테스트나 평가에 대한 이론적 가정/예측에만 근거해서는 안 됩니다. 평가의 운명을 결정하기 위한 독립적인 단계가 아니라 검사 설계의 일부로 문항 모수 추정 및 모델 적합도를 검토할 것을 권장합니다.</p>
</section>
</section>
<section id="요약" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="요약"><span class="header-section-number">5.6</span> 요약</h2>
<p>이 장에서는 이분 문항 응답에 대한 단일차원 IRT 모델을 소개하고 mirt 패키지의 mirt 함수를 사용하여 이러한 모델을 추정하는 방법을 설명했습니다. 이 장에서 소개한 IRT 모델은 단일차원 검사 구조에서 이분법적으로 채점된 문항(예: 옳음 또는 그름, 동의 또는 비동의, 예 또는 아니오)에 적합합니다. mirt 함수는 이분 문항에 대한 일반적인 IRT 모델을 추정할 수 있습니다. 또한 사용자는 추가 요소를 추가하여 보다 전문화되거나 제약된 모델을 만들 수 있습니다(예: 모든 문항에서 하부 점근 모수가 동일하도록 제약). mirt 함수 외에도 문항 및 검사 수준에서 IRT 그래프를 생성하기 위한 mirt 패키지의 여러 그래픽 도구를 설명했습니다. 그런 다음 mirt 패키지의 fscores 함수를 사용하여 잠재 특성 추정치를 얻는 방법을 보여주었습니다. 이 함수는 MLE, EAP, MAP 접근법을 사용하여 잠재 특성 수준을 추정할 수 있습니다. 마지막으로 IRT의 모델 진단에 대한 섹션을 제공했습니다. 이 섹션에서는 문항 적합도, 피험자 적합도 및 전체 모델 적합도를 검사하기 위한 itemfit, personfit 및 anova 함수를 보여줍니다. 관심 있는 독자는 IRT 모델링에 사용할 수 있는 다른 R 패키지에 대한 설명을 보려면 CRAN의 “심리측정 작업 보기(Psychometrics Task View)”(Mair &amp; Hatzinger, 2007b)를 확인해 보시기 바랍니다(CRAN 작업 보기에 대한 자세한 내용은 제12장 참조). 다음 장에서는 다분 문항에 대한 단일차원 IRT 모델에 중점을 둡니다.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>이를 측정 불변성 또는 차별기능문항이라고 합니다. 이 주제는 제11장에 제시되어 있습니다.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>교육에서는 일반적으로 문항에 올바르게 응답하는 것에 대해 이야기합니다. 심리학이나 의학처럼 정답 없는 설문조사에 응답할 수도 있는 다른 환경에서는 일반적으로 문항을 지지할 확률에 대해 생각합니다. 따라서 이러한 분야의 독자는 해당 문구를 안전하게 대체할 수 있습니다.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>기술적으로는 5가지가 있지만, Rasch 모델은 1모수 IRT 모델의 특수한 경우로 간주됩니다.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>다음 장에서 이러한 모델에 대해 자세히 설명합니다.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>참고로 방정식 5.3에서 a를 1로 설정하여 Rasch 모델을 도출합니다.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chap04.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">측정에서 요인분석적 접근</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chap06.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">다분 문항반응이론</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>